"""Bounded readers for generated local Studio/report artifacts."""

from __future__ import annotations

import csv
import os
import stat
from dataclasses import dataclass
from hashlib import sha256
from pathlib import Path
from typing import Any, Literal, NoReturn

import pandas as pd

from reconforge.io.ingress import FileIngressError, TabularIngressPolicy, validate_tabular_input
from reconforge.io.structured import (
    StructuredDocumentError,
    StructuredDocumentPolicy,
    read_json_document,
)

GENERATED_ARTIFACT_INGRESS_PROFILE = "generated-artifact-ingress-v1"
GENERATED_ARTIFACT_MAX_FILE_BYTES = 64 * 1024 * 1024
GENERATED_ARTIFACT_MAX_ROWS = 250_000
GENERATED_ARTIFACT_MAX_COLUMNS = 512
GENERATED_ARTIFACT_MAX_CELLS = 10_000_000
GENERATED_ARTIFACT_MAX_FIELD_CHARACTERS = 128_000
GENERATED_ARTIFACT_JSON_MAX_NODES = 1_000_000
GENERATED_ARTIFACT_JSON_MAX_DEPTH = 64
GENERATED_ARTIFACT_JSON_MAX_COLLECTION_ITEMS = 250_000
GENERATED_ARTIFACT_JSON_MAX_SCALAR_CHARACTERS = 1_000_000
GENERATED_ARTIFACT_CSV_POLICY = TabularIngressPolicy(
    max_file_bytes=GENERATED_ARTIFACT_MAX_FILE_BYTES,
    max_rows=GENERATED_ARTIFACT_MAX_ROWS,
    max_columns=GENERATED_ARTIFACT_MAX_COLUMNS,
    max_cells=GENERATED_ARTIFACT_MAX_CELLS,
    max_csv_field_characters=GENERATED_ARTIFACT_MAX_FIELD_CHARACTERS,
)
GENERATED_ARTIFACT_JSON_POLICY = StructuredDocumentPolicy(
    max_file_bytes=GENERATED_ARTIFACT_MAX_FILE_BYTES,
    max_nodes=GENERATED_ARTIFACT_JSON_MAX_NODES,
    max_depth=GENERATED_ARTIFACT_JSON_MAX_DEPTH,
    max_collection_items=GENERATED_ARTIFACT_JSON_MAX_COLLECTION_ITEMS,
    max_scalar_characters=GENERATED_ARTIFACT_JSON_MAX_SCALAR_CHARACTERS,
    max_yaml_aliases=1,
)
_READ_CHUNK_BYTES = 1024 * 1024
GeneratedCsvMode = Literal["display", "exact-text"]
GeneratedJsonMode = Literal["display", "exact-text"]


class GeneratedArtifactError(ValueError):
    """Safe generated-artifact rejection containing no path or source value."""

    def __init__(self, code: str) -> None:
        self.code = code
        super().__init__(f"Generated artifact rejected ({code}).")


@dataclass(frozen=True)
class GeneratedCsvDocument:
    """One dataframe bound to the exact generated CSV bytes parsed."""

    source_path: Path
    frame: pd.DataFrame
    checksum_sha256: str
    size_bytes: int
    mode: GeneratedCsvMode
    profile_id: str = GENERATED_ARTIFACT_INGRESS_PROFILE


@dataclass(frozen=True)
class GeneratedJsonValueDocument:
    """One JSON value bound to the exact generated bytes parsed."""

    source_path: Path
    payload: object
    checksum_sha256: str
    size_bytes: int
    profile_id: str = GENERATED_ARTIFACT_INGRESS_PROFILE
    mode: GeneratedJsonMode = "exact-text"


@dataclass(frozen=True)
class GeneratedJsonDocument:
    """One object payload bound to the exact generated JSON bytes parsed."""

    source_path: Path
    payload: dict[str, Any]
    checksum_sha256: str
    size_bytes: int
    profile_id: str = GENERATED_ARTIFACT_INGRESS_PROFILE
    mode: GeneratedJsonMode = "exact-text"


def _reject(code: str) -> NoReturn:
    raise GeneratedArtifactError(code)


def _path_is_reparse(path: Path) -> bool:
    try:
        metadata = path.lstat()
    except OSError as exc:
        raise GeneratedArtifactError("generated_file_unreadable") from exc
    file_attributes = getattr(metadata, "st_file_attributes", 0)
    reparse_attribute = getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400)
    return stat.S_ISLNK(metadata.st_mode) or bool(file_attributes & reparse_attribute)


def _bounded_fingerprint(path: Path, *, max_file_bytes: int) -> tuple[str, int]:
    if _path_is_reparse(path):
        _reject("generated_file_not_regular")
    try:
        metadata = path.lstat()
        if not stat.S_ISREG(metadata.st_mode):
            _reject("generated_file_not_regular")
        if metadata.st_size <= 0:
            _reject("generated_file_empty")
        if metadata.st_size > max_file_bytes:
            _reject("generated_file_size_limit")
        digest = sha256()
        total = 0
        with path.open("rb") as handle:
            if os.fstat(handle.fileno()).st_size != metadata.st_size:
                _reject("generated_file_changed")
            for chunk in iter(lambda: handle.read(_READ_CHUNK_BYTES), b""):
                total += len(chunk)
                if total > max_file_bytes:
                    _reject("generated_file_size_limit")
                digest.update(chunk)
            if total != metadata.st_size or os.fstat(handle.fileno()).st_size != metadata.st_size:
                _reject("generated_file_changed")
    except GeneratedArtifactError:
        raise
    except OSError as exc:
        raise GeneratedArtifactError("generated_file_unreadable") from exc
    return digest.hexdigest(), total


def _require_stable(
    path: Path,
    *,
    checksum: str,
    size_bytes: int,
    max_file_bytes: int,
) -> None:
    after_checksum, after_size = _bounded_fingerprint(path, max_file_bytes=max_file_bytes)
    if checksum != after_checksum or size_bytes != after_size:
        _reject("generated_file_changed")


def _validate_csv_header(path: Path) -> None:
    try:
        with path.open("r", encoding="utf-8-sig", errors="strict", newline="") as handle:
            header = next(csv.reader(handle, strict=True), None)
    except (OSError, UnicodeError, csv.Error) as exc:
        raise GeneratedArtifactError("generated_csv_invalid") from exc
    if (
        header is None
        or any(not field.strip() for field in header)
        or len(header) != len(set(header))
    ):
        _reject("generated_csv_header_ambiguous")


def read_generated_csv_document(
    path: Path,
    *,
    mode: GeneratedCsvMode = "display",
) -> GeneratedCsvDocument:
    """Read a bounded generated CSV using explicit display or exact-text typing."""

    if mode not in {"display", "exact-text"}:
        _reject("generated_csv_mode_unsupported")
    if path.suffix.lower() != ".csv":
        _reject("generated_file_type_unsupported")
    checksum, size_bytes = _bounded_fingerprint(
        path,
        max_file_bytes=GENERATED_ARTIFACT_CSV_POLICY.max_file_bytes,
    )
    try:
        inspection = validate_tabular_input(path, policy=GENERATED_ARTIFACT_CSV_POLICY)
        _validate_csv_header(path)
        frame = pd.read_csv(
            path,
            keep_default_na=False,
            dtype=str if mode == "exact-text" else None,
        )
    except FileIngressError as exc:
        raise GeneratedArtifactError(exc.code) from exc
    except (OSError, UnicodeError, pd.errors.ParserError) as exc:
        raise GeneratedArtifactError("generated_csv_invalid") from exc
    if len(frame) != inspection.rows or len(frame.columns) != inspection.columns:
        _reject("generated_file_changed")
    _require_stable(
        path,
        checksum=checksum,
        size_bytes=size_bytes,
        max_file_bytes=GENERATED_ARTIFACT_CSV_POLICY.max_file_bytes,
    )
    return GeneratedCsvDocument(path, frame, checksum, size_bytes, mode)


def verify_generated_csv_document(document: GeneratedCsvDocument) -> None:
    """Verify that a generated CSV document still names the parsed bytes."""

    _require_stable(
        document.source_path,
        checksum=document.checksum_sha256,
        size_bytes=document.size_bytes,
        max_file_bytes=GENERATED_ARTIFACT_CSV_POLICY.max_file_bytes,
    )


def read_generated_json_value_document(
    path: Path,
    *,
    policy: StructuredDocumentPolicy | None = None,
    profile_id: str = GENERATED_ARTIFACT_INGRESS_PROFILE,
    mode: GeneratedJsonMode = "exact-text",
) -> GeneratedJsonValueDocument:
    """Read one bounded generated JSON value with stable-byte provenance.

    Callers with a narrower generated-local contract may supply a named policy
    while retaining the shared regular-file, stable-byte, duplicate-key, and
    non-finite-number controls.
    """

    resolved_policy = policy or GENERATED_ARTIFACT_JSON_POLICY
    if mode not in {"display", "exact-text"}:
        _reject("generated_json_mode_unsupported")
    if not profile_id.strip():
        _reject("generated_profile_invalid")
    if path.suffix.lower() != ".json":
        _reject("generated_file_type_unsupported")
    checksum, size_bytes = _bounded_fingerprint(
        path,
        max_file_bytes=resolved_policy.max_file_bytes,
    )
    try:
        payload = read_json_document(
            path,
            preserve_float_lexemes=mode == "exact-text",
            policy=resolved_policy,
        )
    except StructuredDocumentError as exc:
        raise GeneratedArtifactError(exc.code) from exc
    _require_stable(
        path,
        checksum=checksum,
        size_bytes=size_bytes,
        max_file_bytes=resolved_policy.max_file_bytes,
    )
    return GeneratedJsonValueDocument(path, payload, checksum, size_bytes, profile_id, mode)


def read_generated_json_document(
    path: Path,
    *,
    policy: StructuredDocumentPolicy | None = None,
    profile_id: str = GENERATED_ARTIFACT_INGRESS_PROFILE,
    mode: GeneratedJsonMode = "exact-text",
) -> GeneratedJsonDocument:
    """Read one bounded generated JSON object with stable-byte provenance."""

    document = read_generated_json_value_document(
        path,
        policy=policy,
        profile_id=profile_id,
        mode=mode,
    )
    if not isinstance(document.payload, dict):
        _reject("generated_json_object_required")
    return GeneratedJsonDocument(
        document.source_path,
        dict(document.payload),
        document.checksum_sha256,
        document.size_bytes,
        document.profile_id,
        document.mode,
    )


__all__ = [
    "GENERATED_ARTIFACT_CSV_POLICY",
    "GENERATED_ARTIFACT_INGRESS_PROFILE",
    "GENERATED_ARTIFACT_JSON_POLICY",
    "GeneratedArtifactError",
    "GeneratedCsvMode",
    "GeneratedCsvDocument",
    "GeneratedJsonDocument",
    "GeneratedJsonMode",
    "GeneratedJsonValueDocument",
    "read_generated_csv_document",
    "read_generated_json_document",
    "read_generated_json_value_document",
    "verify_generated_csv_document",
]
