"""Foreign receivables compose the established native AR and functional GL."""

from typing import Any, Protocol

from reconforge.domain.finance_posting import PostingActor
from reconforge.domain.operational_fx_tax import ForeignInvoicePreparation, HistoricalRate


class OperationalFxTaxRepositoryProtocol(Protocol):
    def prepare_invoice(self, request: ForeignInvoicePreparation, *, command_id: str, actor: PostingActor) -> dict[str, Any]: ...
    def prepare_settlement(self, source_id: str, *, foreign_minor: int, settlement_rate: HistoricalRate,
                           period_id: str, posting_date: str, reason: str, command_id: str, actor: PostingActor) -> dict[str, Any]: ...
    def prepare_revaluation(self, source_id: str, *, closing_rate: HistoricalRate, unrealized_gain_account_code: str,
                            unrealized_loss_account_code: str, period_id: str, posting_date: str, reason: str,
                            command_id: str, actor: PostingActor) -> dict[str, Any]: ...
    def prepare_revaluation_reversal(self, source_id: str, *, original_revaluation_id: str, period_id: str,
                                    posting_date: str, reason: str, command_id: str, actor: PostingActor) -> dict[str, Any]: ...
    def review(self, plan_id: str, *, expected_plan_digest: str, reason: str, command_id: str, actor: PostingActor) -> dict[str, Any]: ...
    def post(self, plan_id: str, *, expected_plan_digest: str, reason: str, command_id: str, actor: PostingActor) -> dict[str, Any]: ...
    def get(self, source_id: str, *, actor: PostingActor) -> dict[str, Any]: ...
    def plan_evidence(self, plan_id: str, *, actor: PostingActor) -> dict[str, Any]: ...
