import { expect, test } from "@playwright/test";
const base = process.env.RECONFORGE_GFO_LIVE_URL;
if (!base) throw new Error("RECONFORGE_GFO_LIVE_URL must name the owned integrated HTTPS GFO runtime.");
const tenant = process.env.RECONFORGE_GFO_JOB_TENANT ?? "local";
const workspace = process.env.RECONFORGE_GFO_JOB_WORKSPACE ?? "default";
const organization = process.env.RECONFORGE_GFO_JOB_ORGANIZATION ?? "ORG-GFO";
const entity = process.env.RECONFORGE_GFO_JOB_ENTITY ?? "ENTITY-GFO";
const password = process.env.RECONFORGE_GFO_LIVE_PASSWORD ?? "Synthetic-Gfo-2026-Only";
test("real persisted job operator lifecycle, read-only controls and mobile", async ({ page }) => {
  await page.goto(`${base}/jobs`);
  await page.getByLabel("Tenant", { exact: true }).fill(tenant);
  await page.getByLabel("Username", { exact: true }).fill("gfo-reader");
  await page.getByLabel("Password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await page.getByLabel("Workspace ID").selectOption(workspace);
  await page.getByLabel("Organization ID").fill(organization);
  await page.getByLabel("Entity ID").fill(entity);
  await page.getByRole("button", { name: "Load execution lane" }).click();
  await page.getByRole("button", { name: "Inspect job: GFO-job-queued" }).click();
  await expect(page.getByText("CREATED", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Cancel job", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await page.getByLabel("Tenant", { exact: true }).fill(tenant);
  await page.getByLabel("Username", { exact: true }).fill("gfo-admin");
  await page.getByLabel("Password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await page.getByLabel("Password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Reauthenticate", exact: true }).click();
  await page.getByLabel("Workspace ID").selectOption(workspace);
  await page.getByLabel("Organization ID").fill(organization);
  await page.getByLabel("Entity ID").fill(entity);
  await page.getByRole("button", { name: "Load execution lane" }).click();
  await page.getByRole("button", { name: "Inspect job: GFO-job-queued" }).click();
  await page.getByRole("button", { name: "Cancel job", exact: true }).click();
  await page.reload();
  await page.getByLabel("Tenant", { exact: true }).fill(tenant);
  await page.getByLabel("Username", { exact: true }).fill("gfo-admin");
  await page.getByLabel("Password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await page.getByLabel("Password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Reauthenticate", exact: true }).click();
  await page.getByLabel("Workspace ID").selectOption(workspace);
  await page.getByLabel("Organization ID").fill(organization);
  await page.getByLabel("Entity ID").fill(entity);
  await page.getByRole("button", { name: "Load execution lane" }).click();
  await page.getByRole("button", { name: "Inspect job: GFO-job-queued" }).click();
  await expect(page.getByText("CANCELLED", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Inspect job: GFO-job-failed" }).click();
  await page.getByRole("button", { name: "Requeue job", exact: true }).click();
  await page.getByRole("button", { name: "Inspect job: GFO-job-failed" }).click();
  await expect(page.getByText("REQUEUED", { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole("main")).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
