"""Selected authority constrains shared mutations, including cached decisions."""
from __future__ import annotations

from dataclasses import replace

import pytest

from reconforge.auth.policy import (
    POLICY_VERSION,
    CentralPolicyEngine,
    PolicyEvaluationContext,
    build_policy_decision_evidence,
    policy_context_digest,
    verify_policy_decision_evidence,
)
from reconforge.auth.policy_cache import PolicyDecisionCache


def _context(resource: str, *, organization: str | None = "org", entity: str | None = "entity") -> PolicyEvaluationContext:
    return PolicyEvaluationContext(
        user_id="manager", username="manager", user_permissions={"master_data.manage"},
        tenant_id="tenant", workspace_id="workspace", organization_id=organization, entity_id=entity,
        authorized_tenant_ids=frozenset({"tenant"}), authorized_workspace_ids=frozenset({"workspace"}),
        authorized_organization_ids=frozenset({"org"}), authorized_entity_ids=frozenset({"entity"}),
        object_type=resource, action="mutate",
    )


@pytest.mark.parametrize("resource,organization,entity", [
    ("master_data.organization", "org", "entity"),
    ("master_data.currency", "org", "entity"),
    ("master_data.currency", "org", None),
    ("master_data.fiscal_period", "org", "entity"),
    ("master_data.fiscal_period", "org", None),
])
def test_shared_mutation_rejects_narrow_selection_despite_parent_grants(resource, organization, entity) -> None:
    decision = CentralPolicyEngine().evaluate(_context(resource, organization=organization, entity=entity), required_permission="master_data.manage")
    assert not decision.allowed
    assert decision.reason_code == "master_data_authority_denied"


@pytest.mark.parametrize("resource,organization", [
    ("master_data.organization", "org"),
    ("master_data.currency", None),
    ("master_data.fiscal_period", None),
])
def test_explicit_broader_selection_and_tenant_service_setup_remain_allowed(resource, organization) -> None:
    engine = CentralPolicyEngine()
    context = _context(resource, organization=organization, entity=None)
    assert engine.evaluate(context, required_permission="master_data.manage").allowed
    assert engine.evaluate(replace(context, organization_id=None, workspace_id=None, principal_type="service_account"), required_permission="master_data.manage").allowed


def test_cache_and_decision_digest_bind_resource_action_and_selected_authority() -> None:
    cache = PolicyDecisionCache()
    context = _context("master_data.organization", entity=None)
    read = replace(context, object_type="master_data.currency", action="read")
    for allowed in (context, read):
        assert cache.evaluate(allowed, required_permission="master_data.manage").allowed
        assert cache.evaluate(allowed, required_permission="master_data.manage").allowed
    denied = replace(read, action="mutate")
    result = cache.evaluate(denied, required_permission="master_data.manage")
    assert not result.allowed
    assert len({policy_context_digest(item) for item in (context, read, denied)}) == 3
    narrowed = replace(context, entity_id="entity")
    assert not cache.evaluate(narrowed, required_permission="master_data.manage").allowed
    assert policy_context_digest(narrowed) != policy_context_digest(context)


def test_equivalent_canonical_evidence_inputs_cannot_change_mutation_authority() -> None:
    canonical = _context("master_data.currency")
    decorated = replace(canonical, object_type=" MASTER_DATA.CURRENCY ", action=" MUTATE ")
    assert policy_context_digest(canonical) == policy_context_digest(decorated)
    for context in (canonical, decorated):
        assert not CentralPolicyEngine().evaluate(context, required_permission="master_data.manage").allowed


# Emitted by the unmodified v1 evaluator before this slice; never regenerated by v2.
LEGACY_V1 = {
    "actor_digest": "2145bcbd784f9f363611de0c55e0afd294a689c3a2936996cb939e23cdbfb527",
    "allowed": True,
    "context_binding": "bound",
    "context_digest": "0ac6b9b89eee41ea275d43e89bf1e0c636698bbdb55f561e6d9838c01cc90135",
    "evaluator": "CentralPolicyEngine",
    "granted_permission_digest": "a510d7eabb502678b6881b130d2714df651a8ffd699bd1c7bd2aa74354bb6486",
    "policy_version": "central-policy-v1",
    "principal_type": "user",
    "reason_code": "policy_allowed",
    "request_id_digest": "eee139da3a33404ab26df0e99ce6afd46245b38e1275d2091cce24038237a6c6",
    "required_permission_digest": "a0b73b169bc95ed42d01f2e944c4dbfabcba5cc67bbd57ba690c9bf2dfa80a19",
    "schema_version": 1,
    "scope_digest": "24dc6cd94cdd2e41b17b4b71b65f948e800cf3c8e7f47bb43265b30d4696fb8e",
    "surface_digest": "c84ad3d14d1701541c7fb32768074db0402ba376b1990dd37846d1f81232d85f",
    "decision_digest": "2492f5a4d9a6ce7796b2b6e826f6d8510f9b386cc72eb705931882ee8814b370",
}


def test_new_v2_evidence_preserves_read_only_verification_of_unchanged_v1() -> None:
    context = _context("master_data.currency")
    decision = CentralPolicyEngine().evaluate(context, required_permission="master_data.manage")
    new = build_policy_decision_evidence(decision, actor_id="manager", required_permissions=frozenset({"master_data.manage"}), surface="synthetic-authority", context=context).to_dict()
    assert POLICY_VERSION == "central-policy-v2"
    assert new["policy_version"] == POLICY_VERSION
    assert verify_policy_decision_evidence(new) == new
    assert verify_policy_decision_evidence(LEGACY_V1) == LEGACY_V1
    with pytest.raises(ValueError, match="digest mismatch"):
        verify_policy_decision_evidence({**LEGACY_V1, "allowed": False})
    with pytest.raises(ValueError, match="version is unsupported"):
        verify_policy_decision_evidence({**LEGACY_V1, "policy_version": "central-policy-v999"})
    with pytest.raises(ValueError, match="version is unsupported"):
        verify_policy_decision_evidence({**LEGACY_V1, "policy_version": []})
