import type { Locale } from "./types";

const en = {
  title: "Operational budget control", intro: "Govern an approved envelope and its retained commitments. Every command is authorized and recorded by the server.",
  tenant: "Tenant", username: "Username", password: "Password", signIn: "Sign in", signOut: "Sign out", stepUp: "Confirm stronger authentication", stepPassword: "Confirmation password",
  scope: "Authorized budget scope", workspace: "Workspace ID", organization: "Organization ID", entity: "Legal entity ID", load: "Load budgets", refresh: "Reload current balances", missing: "Choose canonical scope IDs from your organization. The server verifies hierarchy and current grants.",
  draft: "Create budget draft", code: "Budget code", name: "Budget name", period: "Fiscal period ID", currency: "Currency code", limit: "Limit in exact minor units", minorHint: "Enter a positive integer in the selected currency's minor units. The server captures its retained precision and rounding policy.", create: "Create draft",
  envelopes: "Budget envelopes", empty: "No budgets in this authorized scope.", open: "Open budget", previous: "Previous page", next: "Next page", details: "Budget details", status: "Status", version: "Version", available: "Available", reserved: "Reserved", consumed: "Consumed", total: "Approved limit", policy: "Retained currency policy", precision: "Decimal places", reason: "Recorded reason", submit: "Submit for independent approval", approve: "Approve budget", independent: "Approval requires a different human from both the preparer and submitter.",
  commitment: "Commitment command", operation: "Operation", Reserve: "Reserve", Release: "Release", Consume: "Consume", amount: "Amount in currency units", date: "Operation date", source: "Source reference", commitmentId: "Commitment ID", execute: "Record commitment", history: "Immutable commitment history", event: "Event ID", remaining: "Remaining", actor: "Actor", evidence: "Recorded evidence", audit: "Audit event", outbox: "Outbox event", digest: "Request digest", truncated: "The API returns the latest 100 events. Older events remain in the retained ledger; this view is incomplete.",
  saved: "The server confirmed the exact command. Current balances are reloaded separately.", conflict: "The server refused this command. Reload current balances before submitting a new command.", denied: "The current identity or scope is not authorized. Reload the identity and choose an authorized scope.", unavailable: "The service could not return current budget data. Reload when available.", invalid: "Check exact amounts, scope IDs, date, currency and required fields.", contract: "The server returned an invalid budget contract. Financial data is hidden.", unknown: "The command outcome is unknown. Retry the retained exact command to recover its receipt. Scope and edits stay locked until the outcome is confirmed.", retry: "Retry exact command", loading: "Loading current server data…", access: "A human identity with budget_control.read is required.", required: "Stronger authentication is required for budget commands.", Draft: "Draft", Submitted: "Submitted", Approved: "Approved", reloadIdentity: "Reload identity",
} as const;
export type BudgetMessage = keyof typeof en;
const ar: Record<BudgetMessage, string> = {
  title: "الرقابة على الميزانية التشغيلية", intro: "إدارة المخصص المعتمد وارتباطاته المحفوظة. يتحقق الخادم من صلاحية كل أمر ويسجل أدلته.",
  tenant: "المستأجر", username: "اسم المستخدم", password: "كلمة المرور", signIn: "تسجيل الدخول", signOut: "تسجيل الخروج", stepUp: "تأكيد المصادقة الأقوى", stepPassword: "كلمة مرور التأكيد",
  scope: "نطاق الميزانية المصرح", workspace: "معرف مساحة العمل", organization: "معرف المؤسسة", entity: "معرف الكيان القانوني", load: "تحميل الميزانيات", refresh: "إعادة تحميل الأرصدة الحالية", missing: "اختر المعرفات الفعلية لنطاق المؤسسة. يتحقق الخادم من التسلسل والصلاحيات الحالية.",
  draft: "إنشاء مسودة ميزانية", code: "رمز الميزانية", name: "اسم الميزانية", period: "معرف الفترة المالية", currency: "رمز العملة", limit: "الحد بوحدات العملة الصغرى الدقيقة", minorHint: "أدخل عدداً صحيحاً موجباً بوحدات العملة الصغرى. يحفظ الخادم دقة العملة وسياسة التقريب.", create: "إنشاء مسودة",
  envelopes: "مخصصات الميزانية", empty: "لا توجد ميزانيات في النطاق المصرح.", open: "فتح الميزانية", previous: "الصفحة السابقة", next: "الصفحة التالية", details: "تفاصيل الميزانية", status: "الحالة", version: "الإصدار", available: "المتاح", reserved: "المحجوز", consumed: "المستهلك", total: "الحد المعتمد", policy: "سياسة العملة المحفوظة", precision: "المنازل العشرية", reason: "السبب المسجل", submit: "إرسال للموافقة المستقلة", approve: "اعتماد الميزانية", independent: "يتطلب الاعتماد شخصاً مختلفاً عن المنشئ والمرسل معاً.",
  commitment: "أمر الارتباط", operation: "العملية", Reserve: "حجز", Release: "تحرير", Consume: "استهلاك", amount: "المبلغ بوحدات العملة", date: "تاريخ العملية", source: "مرجع المصدر", commitmentId: "معرف الارتباط", execute: "تسجيل الارتباط", history: "سجل الارتباطات غير القابل للتعديل", event: "معرف الحدث", remaining: "المتبقي", actor: "الفاعل", evidence: "الأدلة المسجلة", audit: "حدث التدقيق", outbox: "حدث صندوق الصادر", digest: "بصمة الطلب", truncated: "تعرض الواجهة أحدث ١٠٠ حدث. تبقى الأحداث الأقدم محفوظة في السجل؛ هذا العرض غير كامل.",
  saved: "أكد الخادم الأمر الدقيق. يعاد تحميل الأرصدة الحالية بصورة مستقلة.", conflict: "رفض الخادم هذا الأمر. أعد تحميل الأرصدة الحالية قبل إرسال أمر جديد.", denied: "الهوية أو النطاق الحالي غير مصرح. أعد تحميل الهوية واختر نطاقاً مصرحاً.", unavailable: "تعذر الحصول على بيانات الميزانية الحالية. أعد التحميل عند توفر الخدمة.", invalid: "راجع المبالغ الدقيقة ومعرفات النطاق والتاريخ والعملة والحقول المطلوبة.", contract: "أعاد الخادم بيانات ميزانية غير صالحة. أخفيت البيانات المالية.", unknown: "نتيجة الأمر غير معروفة. أعد محاولة الأمر الدقيق المحفوظ لاسترجاع إيصاله. يبقى النطاق والتحرير مقفلين حتى تأكيد النتيجة.", retry: "إعادة محاولة الأمر الدقيق", loading: "تحميل البيانات الحالية من الخادم…", access: "يتطلب العرض هوية بشرية بصلاحية قراءة الميزانية.", required: "تتطلب أوامر الميزانية مصادقة أقوى.", Draft: "مسودة", Submitted: "مرسلة", Approved: "معتمدة", reloadIdentity: "إعادة تحميل الهوية",
};
export const budgetTranslate = (locale: Locale, key: BudgetMessage): string => (locale === "ar" ? ar : en)[key];
