import { describe, expect, it } from "vitest";
import { majorToMinor, parseOpening, parseReportingMap, reportingCommand, reportingMoney } from "./financial-reporting-data";
const scope = { workspace_id: "w", organization_id: "o", legal_entity_id: "e" };
describe("exact classified financial data", () => {
  it("preserves large values and requires currency precision without rounding", () => { expect(majorToMinor("90071992547409.93", 2)).toBe("9007199254740993"); expect(reportingMoney("-9007199254740993", 2)).toBe("-90071992547409.93"); expect(majorToMinor("12.345", 3)).toBe("12345"); expect(() => majorToMinor("12.345", 2)).toThrow(); expect(() => majorToMinor("1e3", 2)).toThrow(); expect(() => majorToMinor("NaN", 2)).toThrow(); });
  it("retains nested command bytes after the user's inputs change", () => { const rows = [{ account_code: "CASH", debit_minor: "9007199254740993", credit_minor: "0" }]; const command = reportingCommand("/api/v1/financial-reporting/openings", { lines: rows }); rows[0].debit_minor = "0"; expect(JSON.parse(command.payloadJson).lines[0].debit_minor).toBe("9007199254740993"); expect(Object.isFrozen(command)).toBe(true); });
  it("rejects self-reviewed mappings and cross-entity responses", () => { const map = { ...scope, id: "map", name: "Explicit", map_digest: "a".repeat(64), status: "Reviewed", preparer_actor_id: "maker", reviewer_actor_id: "maker", review_digest: "b".repeat(64), accounts: [{ account_id: "cash", account_code: "CASH", account_name: "Cash", account_type: "Asset", normal_balance: "Debit", section: "CurrentAsset", is_cash: true }] }; expect(() => parseReportingMap(map, scope)).toThrow(); map.reviewer_actor_id = "checker"; expect(parseReportingMap(map, scope).status).toBe("Reviewed"); expect(() => parseReportingMap(map, { ...scope, legal_entity_id: "other" })).toThrow(); });
  it("refuses an opening with a posted label but no real effect or unequal money", () => { const plan = { ...scope, id: "OB1-plan", map_id: "map", entry_id: "entry", plan_digest: "a".repeat(64), status: "Posted", currency_code: "USD", currency_precision: 2, amount_minor: "10000", preparer_actor_id: "maker", reviewer_actor_id: "checker", posting_effect_id: null, lines: [{ account_code: "CASH", debit_minor: "10000", credit_minor: "0" }, { account_code: "EQUITY", debit_minor: "0", credit_minor: "10000" }] }; expect(() => parseOpening(plan, scope)).toThrow(); const valid = { ...plan, posting_effect_id: "posting" }; expect(parseOpening(valid, scope).amount_minor).toBe("10000"); valid.lines[1].credit_minor = "9999"; expect(() => parseOpening(valid, scope)).toThrow(); });
});
