import { AdminApiError } from "./data";
import type { BrowserAdminSession } from "./types";
import type { FinanceScope } from "./enterprise-finance-data";

export type Section = "CurrentAsset" | "NonCurrentAsset" | "CurrentLiability" | "NonCurrentLiability" | "Equity" | "Income" | "Expense";
export const statementSections: readonly Section[] = ["CurrentAsset", "NonCurrentAsset", "CurrentLiability", "NonCurrentLiability", "Equity", "Income", "Expense"];
export interface ClassifiedAccount { account_id: string; account_code: string; account_name: string; account_type: string; normal_balance: string; section: Section; is_cash: boolean }
export interface ReportingMap extends FinanceScope { id: string; name: string; map_digest: string; status: "Draft" | "Reviewed"; preparer_actor_id: string; reviewer_actor_id: string | null; review_digest: string | null; accounts: ClassifiedAccount[] }
export interface Opening extends FinanceScope { id: string; map_id: string; entry_id: string; plan_digest: string; status: "Draft" | "Reviewed" | "Posted"; currency_code: string; currency_precision: number; amount_minor: string; preparer_actor_id: string; reviewer_actor_id: string | null; posting_effect_id: string | null; lines: { account_code: string; debit_minor: string; credit_minor: string }[] }
export interface Catalog extends FinanceScope { currency_code: string; currency_precision: number; accounts: Omit<ClassifiedAccount, "section" | "is_cash">[]; periods: { id: string; name: string; start_date: string; end_date: string; status: string }[]; journals: { journal_code: string; name: string; currency_code: string }[] }
export interface Phase { debit_minor: string; credit_minor: string; balance_minor: string; debit_balance_minor: string; credit_balance_minor: string }
export interface Contribution { effect_id: string; entry_id: string; posting_date: string; phase: "opening" | "activity"; line_number: number; debit_minor: string; credit_minor: string }
export interface StatementAccount extends ClassifiedAccount { opening: Phase; activity: Phase; closing: Phase; postings: Contribution[] }
export interface Statements extends FinanceScope { map_id: string; map_digest: string; report_digest: string; balances_digest: string; period_start: string; as_of_date: string; effect_count: number; currency_policy: null | { currency_code: string; currency_precision: number }; trial_balance: { accounts: StatementAccount[]; totals: unknown }; balance_sheet: { assets_minor: string; liabilities_minor: string; equity_minor: string; accumulated_unclosed_result_minor: string; balanced: boolean }; income_statement: { income_minor: string; expense_minor: string; result_minor: string }; cash_movements: { opening_minor: string; activity_minor: string; closing_minor: string; inflow_minor: string; outflow_minor: string; movements: { effect_id: string; entry_id: string; posting_date: string; movement_kind: string; cash_delta_minor: string; cash_lines: Contribution[]; counterpart_lines: Contribution[] }[] } }
export interface ReportingCommand { readonly path: string; readonly payloadJson: string; readonly commandId: string }
const object = (v: unknown): v is Record<string, unknown> => v !== null && typeof v === "object" && !Array.isArray(v);
const text = (v: unknown): v is string => typeof v === "string" && v.length > 0 && v.length <= 500 && !/[\x00-\x1f\x7f]/.test(v);
const minor = (v: unknown): v is string => typeof v === "string" && /^-?(0|[1-9]\d{0,30})$/.test(v);
const digest = (v: unknown): v is string => typeof v === "string" && /^[a-f0-9]{64}$/.test(v);
const precision = (v: unknown): v is number => typeof v === "number" && Number.isInteger(v) && v >= 0 && v <= 8;
function invalid(): never { throw new Error("financial_reporting_contract_invalid"); }
function scoped(v: unknown, scope: FinanceScope): asserts v is Record<string, unknown> { if (!object(v) || Object.entries(scope).some(([key, expected]) => v[key] !== expected)) invalid(); }
function classified(v: unknown): asserts v is Record<string, unknown> { if (!object(v) || !["account_id", "account_code", "account_name", "account_type", "normal_balance"].every(key => text(v[key])) || !statementSections.includes(v.section as Section) || typeof v.is_cash !== "boolean" || (v.is_cash && v.section !== "CurrentAsset")) invalid(); }
export function parseReportingMap(v: unknown, scope: FinanceScope): ReportingMap {
  scoped(v, scope); if (!text(v.id) || !text(v.name) || !digest(v.map_digest) || !text(v.preparer_actor_id) || !Array.isArray(v.accounts) || !v.accounts.length || v.accounts.length > 1000 || !["Draft", "Reviewed"].includes(String(v.status))) invalid();
  const ids = new Set<string>(); for (const row of v.accounts) { classified(row); if (ids.has(String(row.account_id))) invalid(); ids.add(String(row.account_id)); }
  if (v.status === "Draft" ? v.reviewer_actor_id !== null || v.review_digest !== null : !text(v.reviewer_actor_id) || v.reviewer_actor_id === v.preparer_actor_id || !digest(v.review_digest)) invalid();
  return v as unknown as ReportingMap;
}
export function parseOpening(v: unknown, scope: FinanceScope): Opening {
  scoped(v, scope); if (!text(v.id) || !text(v.map_id) || !text(v.entry_id) || !digest(v.plan_digest) || !text(v.currency_code) || !precision(v.currency_precision) || !minor(v.amount_minor) || BigInt(v.amount_minor) <= 0n || !["Draft", "Reviewed", "Posted"].includes(String(v.status)) || !text(v.preparer_actor_id) || !Array.isArray(v.lines) || v.lines.length < 2 || v.lines.length > 64) invalid();
  let dr = 0n, cr = 0n; const codes = new Set<string>(); for (const line of v.lines) { if (!object(line) || !text(line.account_code) || codes.has(line.account_code) || !minor(line.debit_minor) || !minor(line.credit_minor) || BigInt(line.debit_minor) < 0n || BigInt(line.credit_minor) < 0n || (BigInt(line.debit_minor) === 0n) === (BigInt(line.credit_minor) === 0n)) invalid(); codes.add(line.account_code); dr += BigInt(line.debit_minor); cr += BigInt(line.credit_minor); }
  if (dr !== cr || dr.toString() !== v.amount_minor || (v.status === "Posted" ? !text(v.posting_effect_id) : v.posting_effect_id !== null) || (v.status === "Draft" ? v.reviewer_actor_id !== null : !text(v.reviewer_actor_id) || v.reviewer_actor_id === v.preparer_actor_id)) invalid();
  return v as unknown as Opening;
}
export function parseCatalog(v: unknown, scope: FinanceScope): Catalog {
  scoped(v, scope); if (!text(v.currency_code) || !/^[A-Z]{3}$/.test(v.currency_code) || !precision(v.currency_precision) || !Array.isArray(v.accounts) || v.accounts.length > 1000 || !Array.isArray(v.periods) || v.periods.length > 200 || !Array.isArray(v.journals) || v.journals.length > 200) invalid();
  for (const row of v.accounts) if (!object(row) || !["account_id", "account_code", "account_name", "account_type", "normal_balance"].every(k => text(row[k]))) invalid();
  for (const row of v.periods) if (!object(row) || !["id", "name", "start_date", "end_date", "status"].every(k => text(row[k]))) invalid();
  for (const row of v.journals) if (!object(row) || !["journal_code", "name", "currency_code"].every(k => text(row[k]))) invalid();
  return v as unknown as Catalog;
}
function phase(v: unknown): asserts v is Phase { if (!object(v) || !["debit_minor", "credit_minor", "balance_minor", "debit_balance_minor", "credit_balance_minor"].every(k => minor(v[k]))) invalid(); const dr = BigInt(String(v.debit_minor)), cr = BigInt(String(v.credit_minor)); if (dr < 0n || cr < 0n || (dr - cr).toString() !== v.balance_minor || (dr > cr ? dr - cr : 0n).toString() !== v.debit_balance_minor || (cr > dr ? cr - dr : 0n).toString() !== v.credit_balance_minor) invalid(); }
export function parseStatements(v: unknown, scope: FinanceScope): Statements {
  scoped(v, scope); if (v.contract_version !== "financial-reporting-v1" || v.balance_scope !== "recorded-postings-business-date-as-of" || !digest(v.report_digest) || !digest(v.map_digest) || !digest(v.balances_digest) || !text(v.map_id) || !text(v.period_start) || !text(v.as_of_date) || typeof v.effect_count !== "number" || !Number.isInteger(v.effect_count) || v.effect_count < 0 || v.effect_count > 1000 || !object(v.trial_balance) || !Array.isArray(v.trial_balance.accounts) || !object(v.balance_sheet) || !object(v.income_statement) || !object(v.cash_movements) || !Array.isArray(v.cash_movements.movements)) invalid();
  if (v.currency_policy !== null && (!object(v.currency_policy) || !text(v.currency_policy.currency_code) || !precision(v.currency_policy.currency_precision))) invalid();
  let dr = 0n, cr = 0n, cashOpening = 0n, cashClosing = 0n; const ids = new Set<string>();
  for (const row of v.trial_balance.accounts) { classified(row); if (ids.has(String(row.account_id)) || !Array.isArray(row.postings)) invalid(); ids.add(String(row.account_id)); phase(row.opening); phase(row.activity); phase(row.closing); if (BigInt(row.opening.debit_minor) + BigInt(row.activity.debit_minor) !== BigInt(row.closing.debit_minor) || BigInt(row.opening.credit_minor) + BigInt(row.activity.credit_minor) !== BigInt(row.closing.credit_minor)) invalid(); dr += BigInt(row.closing.debit_minor); cr += BigInt(row.closing.credit_minor); if (row.is_cash) { cashOpening += BigInt(row.opening.balance_minor); cashClosing += BigInt(row.closing.balance_minor); } }
  if (dr !== cr) invalid();
  for (const [row, keys] of [[v.balance_sheet, ["assets_minor", "liabilities_minor", "equity_minor", "accumulated_unclosed_result_minor"]], [v.income_statement, ["income_minor", "expense_minor", "result_minor"]], [v.cash_movements, ["opening_minor", "activity_minor", "closing_minor", "inflow_minor", "outflow_minor"]]] as const) if (keys.some(k => !minor(row[k]))) invalid();
  const bs = v.balance_sheet, income = v.income_statement, cash = v.cash_movements;
  if (bs.balanced !== true || BigInt(String(bs.assets_minor)) !== BigInt(String(bs.liabilities_minor)) + BigInt(String(bs.equity_minor)) + BigInt(String(bs.accumulated_unclosed_result_minor)) || BigInt(String(income.result_minor)) !== BigInt(String(income.income_minor)) - BigInt(String(income.expense_minor)) || cashOpening.toString() !== cash.opening_minor || cashClosing.toString() !== cash.closing_minor || (cashClosing - cashOpening).toString() !== cash.activity_minor) invalid();
  let movement = 0n; const effects = new Set<string>(); for (const row of cash.movements as unknown[]) { if (!object(row) || !text(row.effect_id) || effects.has(row.effect_id) || !text(row.entry_id) || !text(row.posting_date) || !minor(row.cash_delta_minor) || !["Inflow", "Outflow", "InternalTransfer", "ZeroNet"].includes(String(row.movement_kind)) || !Array.isArray(row.cash_lines) || !Array.isArray(row.counterpart_lines)) invalid(); effects.add(row.effect_id); movement += BigInt(row.cash_delta_minor); }
  if (movement.toString() !== cash.activity_minor) invalid();
  return v as unknown as Statements;
}
export function majorToMinor(value: string, places: number): string { if (!precision(places) || !/^(0|[1-9]\d*)(\.\d+)?$/.test(value)) invalid(); const [whole, fraction = ""] = value.split("."); if (fraction.length > places) invalid(); const result = BigInt(whole) * 10n ** BigInt(places) + BigInt(fraction.padEnd(places, "0") || "0"); if (result > 9000000000000000000n) invalid(); return result.toString(); }
export function reportingMoney(value: string, places: number): string { if (!minor(value) || !precision(places)) invalid(); const negative = value.startsWith("-"), digits = (negative ? value.slice(1) : value).padStart(places + 1, "0"); return `${negative ? "-" : ""}${places ? `${digits.slice(0, -places)}.${digits.slice(-places)}` : digits}`; }
export function reportingCommand(path: string, body: Readonly<Record<string, unknown>>): ReportingCommand { if (!path.startsWith("/api/v1/financial-reporting/")) invalid(); const commandId = crypto.randomUUID(); return Object.freeze({ path, commandId, payloadJson: JSON.stringify({ ...body, command_id: commandId }) }); }
export async function reportingRequest(session: BrowserAdminSession, scope: FinanceScope, path: string, command?: ReportingCommand, signal?: AbortSignal): Promise<Record<string, unknown>> {
  if (!Object.values(scope).every(text) || !path.startsWith("/api/v1/financial-reporting/") || (command && (!session.csrfToken || command.path !== path))) invalid();
  const response = await fetch(path, { credentials: "same-origin", cache: "no-store", signal, method: command ? "POST" : "GET", headers: { Accept: "application/json", "X-ReconForge-Tenant": session.tenantId, "X-ReconForge-Workspace": scope.workspace_id, "X-ReconForge-Organization": scope.organization_id, "X-ReconForge-Legal-Entity": scope.legal_entity_id, ...(command ? { "Content-Type": "application/json", "X-ReconForge-CSRF": session.csrfToken } : {}) }, ...(command ? { body: command.payloadJson } : {}) });
  if (!response.ok) { let code = `http_${response.status}`; try { const value: unknown = await response.json(); if (object(value) && object(value.error) && text(value.error.code)) code = value.error.code; } catch { /* HTTP status remains authoritative. */ } throw new AdminApiError(response.status, code); }
  const value: unknown = await response.json(); if (!object(value) || value.api_contract_version !== "financial-reporting-api-v1") invalid(); return value;
}
