import { statementSections } from "./financial-reporting-data";

const scope = { workspace_id: "work", organization_id: "org", legal_entity_id: "entity" };
export function snapshotFixture() {
  const value = "90071992547409930000000000000000001", zero = "0";
  const phase = (credit = false, empty = false) => ({ debit_minor: credit || empty ? zero : value, credit_minor: credit && !empty ? value : zero, balance_minor: empty ? zero : credit ? `-${value}` : value, debit_balance_minor: credit || empty ? zero : value, credit_balance_minor: credit && !empty ? value : zero });
  const total = (empty = false) => ({ effect_count: empty ? 0 : 1001, turnover_totals: { debit_minor: empty ? zero : value, credit_minor: empty ? zero : value, balanced: true }, balance_totals: { debit_minor: empty ? zero : value, credit_minor: empty ? zero : value, balanced: true } });
  return { contract_version: "financial-reporting-snapshot-v1", balance_scope: "immutable-captured-native-postings", ...scope, id: "FRS1-report", map_id: "map", map_digest: "a".repeat(64), report_digest: "b".repeat(64), evidence_digest: "c".repeat(64), period_id: "period", period_start: "2026-10-01", period_end: "2026-10-31", as_of_date: "2026-10-31", captured_at: "2026-11-01T00:00:00Z", effect_count: 1001, line_count: 2002, currency_policy: { currency_code: "JPY", currency_precision: 0 }, trial_balance: { accounts: [
    { account_id: "cash", account_code: "CASH", account_name: "Cash", account_type: "Asset", normal_balance: "Debit", section: "CurrentAsset", is_cash: true, opening: phase(false, true), activity: phase(), closing: phase(), line_count: 1001 },
    { account_id: "income", account_code: "INCOME", account_name: "Income", account_type: "Income", normal_balance: "Credit", section: "Income", is_cash: false, opening: phase(true, true), activity: phase(true), closing: phase(true), line_count: 1001 },
  ], totals: { opening: total(true), activity: total(), closing: total() } }, sections: Object.fromEntries(statementSections.map(section => [section, { opening_minor: zero, activity_minor: ["Income", "CurrentAsset"].includes(section) ? value : zero, closing_minor: ["Income", "CurrentAsset"].includes(section) ? value : zero }])), balance_sheet: { assets_minor: value, liabilities_minor: zero, equity_minor: zero, accumulated_unclosed_result_minor: value, balanced: true }, income_statement: { income_minor: value, expense_minor: zero, result_minor: value }, cash_movements: { opening_minor: zero, activity_minor: value, closing_minor: value, inflow_minor: value, outflow_minor: zero, movement_count: 1001 } };
}
