import { describe, expect, it } from "vitest";
import { parseAssetDetail, parseAssetPlan, parseAssetSummary } from "./fixed-assets-data";
const scope = { workspace_id: "work", organization_id: "org", legal_entity_id: "entity" };
const summary = { ...scope, id: "asset", asset_number: "MACHINE", name: "Equipment", cost_minor: "9007199254740993", salvage_minor: "0", useful_life_months: 3, currency_code: "USD", currency_precision: 2, asset_digest: "a".repeat(64), acquired: true, disposed: false, accumulated_minor: "3002399751580331", months: 1, sequence: 2 };
const plan = { ...scope, id: "plan", asset_id: "asset", entry_id: "entry", kind: "depreciate", phase: 1, status: "Reviewed", posting_date: "2026-11-01", period_id: "nov", amount_minor: "3002399751580331", accumulated_before_minor: "0", proceeds_minor: "0", months_after: 1, sequence: 1, currency_code: "USD", currency_precision: 2, plan_digest: "b".repeat(64), validation_digest: "c".repeat(64), preparer_actor_id: "maker", reviewer_actor_id: "checker", posting_effect_id: null, snapshot: { entry: { ...scope, id: "entry", currency_code: "USD", currency_precision: 2, posting_date: "2026-11-01", period_id: "nov", preparer_actor_id: "maker" }, lines: [{ line_number: 1, account_id: "expense", debit_minor: "3002399751580331", credit_minor: "0", description: "Depreciation" }, { line_number: 2, account_id: "accum", debit_minor: "0", credit_minor: "3002399751580331", description: "Depreciation" }] } };
describe("fixed asset exact source and native GL boundary", () => {
  it("retains JS-unsafe exact minor strings and verified balanced lines", () => { expect(parseAssetSummary(summary, scope).cost_minor).toBe("9007199254740993"); expect(parseAssetPlan(plan, scope).amount_minor).toBe("3002399751580331"); });
  it.each(["cost_minor", "salvage_minor", "accumulated_minor"])("rejects numerical or malformed %s", field => { expect(() => parseAssetSummary({ ...summary, [field]: 1 }, scope)).toThrow(); expect(() => parseAssetSummary({ ...summary, [field]: "1.0" }, scope)).toThrow(); });
  it("rejects foreign scope and excess depreciation", () => { expect(() => parseAssetSummary({ ...summary, legal_entity_id: "foreign" }, scope)).toThrow(); expect(() => parseAssetSummary({ ...summary, accumulated_minor: "9007199254740994" }, scope)).toThrow(); });
  it("rejects unbalanced native lines and self review", () => { expect(() => parseAssetPlan({ ...plan, reviewer_actor_id: "maker" }, scope)).toThrow(); expect(() => parseAssetPlan({ ...plan, snapshot: { lines: [plan.snapshot.lines[0], { ...plan.snapshot.lines[1], credit_minor: "1" }] } }, scope)).toThrow(); });
  it("rejects a native snapshot from another entity or currency", () => { expect(() => parseAssetPlan({ ...plan, snapshot: { ...plan.snapshot, entry: { ...plan.snapshot.entry, legal_entity_id: "foreign" } } }, scope)).toThrow(); expect(() => parseAssetPlan({ ...plan, snapshot: { ...plan.snapshot, entry: { ...plan.snapshot.entry, currency_code: "EUR" } } }, scope)).toThrow(); });
  it("verifies carrying value and chronological evidence affinity", () => { const detail = { ...summary, status: "Active", carrying_minor: "6004799503160662", plans: [plan], history_before: null }; expect(parseAssetDetail(detail, scope).carrying_minor).toBe("6004799503160662"); expect(() => parseAssetDetail({ ...detail, carrying_minor: "6004799503160663" }, scope)).toThrow(); expect(() => parseAssetDetail({ ...detail, plans: [{ ...plan, asset_id: "another" }] }, scope)).toThrow(); });
});
