import type { Locale } from "./types";
const en = {
  title: "Purchase to pay", intro: "Approved purchase orders, reviewed stock receiving, three-way matched supplier invoices and governed ledger payments.",
  signIn: "Sign in", signOut: "Sign out", tenant: "Tenant", username: "Username", password: "Password", stepUp: "Verify identity", scope: "Organization and legal entity", workspace: "Workspace",
  load: "Load", refresh: "Refresh", newOrder: "New stock purchase", number: "Purchase number", supplier: "Supplier", item: "Item", quantity: "Quantity", unitPrice: "Unit price in minor units", date: "Posting date", period: "Open fiscal period", location: "Receiving location", policy: "FIFO valuation policy", journal: "Accrual and payment journal", ap: "Accounts payable", cash: "Cash account", create: "Create purchase order",
  cycles: "Purchases", empty: "No purchases in this scope.", open: "Open", stage: "Stage", amount: "Total in minor units", reason: "Review or posting reason", execute: "Execute", saved: "Command committed", unknown: "The response was lost or could not be verified. Retry the retained command before continuing.", retry: "Retry the same command", denied: "Current identity or scope cannot perform this operation.", conflict: "The source changed or the command conflicts. Reload its current result.", unavailable: "The PostgreSQL service or response is unavailable.", pending: "Pending command", evidence: "Source and ledger references", noReferences: "Create the supplier and active inventory/finance master references before starting a purchase.", independent: "Preparation, review and posting require independent authorized people. Payment posting and settlement also require independence from the invoice creator and approver.",
  "submit-order": "Submit purchase order", "approve-order": "Approve purchase order", "prepare-receipt": "Prepare receiving", "review-receipt": "Review receiving", receive: "Post stock receiving and GL", "match-invoice": "Create and match supplier invoice", "approve-invoice": "Approve supplier invoice", "prepare-accrual": "Prepare invoice accrual", "review-accrual": "Review invoice accrual", "post-accrual": "Post invoice accrual", "prepare-payment": "Prepare payment", "review-payment": "Review payment", pay: "Post payment and settle AP",
  Draft: "Draft order", Submitted: "Submitted order", Approved: "Approved order", ReceiptPrepared: "Receiving prepared", ReceiptReviewed: "Receiving reviewed", Received: "Received", InvoiceMatched: "Invoice matched", InvoiceApproved: "Invoice approved", AccrualPrepared: "Accrual prepared", AccrualReviewed: "Accrual reviewed", Accrued: "Invoice accrued", PaymentPrepared: "Payment prepared", PaymentReviewed: "Payment reviewed", Paid: "Paid",
} as const;
const ar: Record<keyof typeof en, string> = {
  title: "من الشراء إلى السداد", intro: "أوامر شراء معتمدة واستلام مخزون مُراجع وفواتير موردين بمطابقة ثلاثية وسداد محاسبي خاضع للصلاحيات.",
  signIn: "تسجيل الدخول", signOut: "تسجيل الخروج", tenant: "المستأجر", username: "اسم المستخدم", password: "كلمة المرور", stepUp: "التحقق من الهوية", scope: "المؤسسة والكيان القانوني", workspace: "مساحة العمل", load: "تحميل", refresh: "تحديث", newOrder: "شراء مخزون جديد", number: "رقم الشراء", supplier: "المورد", item: "الصنف", quantity: "الكمية", unitPrice: "سعر الوحدة بالوحدات النقدية الصغرى", date: "تاريخ القيد", period: "الفترة المالية المفتوحة", location: "موقع الاستلام", policy: "سياسة تقييم FIFO", journal: "دفتر الاستحقاق والسداد", ap: "حساب الموردين", cash: "الحساب النقدي", create: "إنشاء أمر الشراء", cycles: "المشتريات", empty: "لا توجد مشتريات في هذا النطاق.", open: "فتح", stage: "المرحلة", amount: "الإجمالي بالوحدات الصغرى", reason: "سبب المراجعة أو الترحيل", execute: "تنفيذ", saved: "تم تثبيت الأمر", unknown: "فُقدت الاستجابة أو تعذر التحقق منها. أعد إرسال الأمر المحفوظ قبل المتابعة.", retry: "إعادة إرسال الأمر نفسه", denied: "الهوية أو النطاق الحالي لا يسمح بهذه العملية.", conflict: "تغير المصدر أو تعارض الأمر. حدّث النتيجة الحالية.", unavailable: "خدمة PostgreSQL أو الاستجابة غير متاحة.", pending: "أمر معلق", evidence: "مراجع المصادر والقيود", noReferences: "أنشئ المورد ومراجع المخزون والمحاسبة النشطة قبل بدء الشراء.", independent: "يتطلب الإعداد والمراجعة والترحيل أشخاصًا مستقلين ذوي صلاحيات. يتطلب ترحيل السداد وتسويته الاستقلال عن مُنشئ فاتورة المورد ومعتمدها.",
  "submit-order": "تقديم أمر الشراء", "approve-order": "اعتماد أمر الشراء", "prepare-receipt": "إعداد الاستلام", "review-receipt": "مراجعة الاستلام", receive: "ترحيل المخزون والقيد", "match-invoice": "إنشاء ومطابقة فاتورة المورد", "approve-invoice": "اعتماد فاتورة المورد", "prepare-accrual": "إعداد استحقاق الفاتورة", "review-accrual": "مراجعة استحقاق الفاتورة", "post-accrual": "ترحيل استحقاق الفاتورة", "prepare-payment": "إعداد السداد", "review-payment": "مراجعة السداد", pay: "ترحيل السداد وتسوية الموردين",
  Draft: "أمر مسودة", Submitted: "أمر مقدم", Approved: "أمر معتمد", ReceiptPrepared: "استلام مُعد", ReceiptReviewed: "استلام مُراجع", Received: "مستلم", InvoiceMatched: "فاتورة مطابقة", InvoiceApproved: "فاتورة معتمدة", AccrualPrepared: "استحقاق مُعد", AccrualReviewed: "استحقاق مُراجع", Accrued: "استحقاق مُرحل", PaymentPrepared: "سداد مُعد", PaymentReviewed: "سداد مُراجع", Paid: "مسدد",
};
export type ProcurementMessage = keyof typeof en;
export function procurementTranslate(locale: Locale, key: ProcurementMessage): string { return (locale === "ar" ? ar : en)[key]; }
