import type { Locale } from "./types";

const en = {
  policyUnverified: "Historical currency precision is unverified. Original minor units remain visible; new financial actions are unavailable until the policy is resolved.", policyAmountHint: "Enter amounts in", policyPrecision: "Decimal places", policyNoRounding: "Extra decimal places are rejected, not rounded.", policyEvidence: "Retained monetary policy", policySource: "Source", policyRounding: "Rounding rule", policyDigest: "Registry digest",
  ar_major_amount_invalid: "Enter a nonnegative amount using the recorded decimal places. Use a dot or Arabic decimal separator, no grouping, and stay within the exact write limit.", ar_monetary_policy_unverified: "This record has no verified historical monetary policy. Read its original minor units; resolve the policy before a new financial action.", ar_monetary_policy_mismatch: "The records have different retained monetary policies. Refresh and resolve their policy differences before applying money.",
  newInvoice: "New invoice", evidenceDetails: "Evidence details",
  cash: "Cash receipts and allocations", cashIntro: "Record money actually received, then apply it to this approved invoice. These actions change receivable balances immediately.", cashReceipt: "New cash receipt", cashNumber: "Receipt number", cashDate: "Receipt date", cashAmount: "Received amount", cashInitialAllocation: "Apply now to this invoice", cashReview: "Review cash action", cashConfirm: "Confirm financial action", cashReviewNote: "Confirm the customer, currency and amounts below against your payment evidence. The server posts this receipt or allocation immediately.", cashAllocated: "Allocated", cashUnallocated: "Unallocated receipt balance", cashReceipts: "Recorded customer receipts", cashSelectReceipt: "Select a recorded receipt", cashAllocation: "Additional allocation", cashAllocateReview: "Review allocation", cashPosted: "Posted", cashNoReceipts: "No receipts were returned for this customer.", cash_balance_invalid: "Use a positive receipt or allocation amount. An allocation must fit both the unapplied receipt amount and the approved invoice balance, in the same customer's currency.", cashRetryLimit: "Three attempts reached. Keep this receipt number for investigation; do not create a replacement until its outcome is verified.", cashUnknown: "The financial result is not confirmed. The exact receipt request is frozen; retrying it uses the same key and values.", cashReadback: "Refresh authoritative receipt and invoice", cashRecovered: "The displayed balances were read from the server. They do not identify whether the earlier request succeeded. Review them before any further financial action.", cashAcknowledge: "Use these current balances", cashReauth: "Reauthenticate for cash actions", cashReauthNote: "A recent human verification is required. Reauthentication clears private drafts; select the workspace again afterward.", cashReauthReady: "Recent verification is active. The server checks it again for each cash action.", cashReauthNeeded: "Reauthenticate above before posting or allocating money.", cashNew: "Prepare another receipt", cashReadOnly: "Cash mutations require an authorized human with receivables.manage.", cashInvoiceBalance: "Current invoice balance", cashNoOpenInvoice: "This invoice has no approved open balance. Recorded receipts remain available for review.", cashSaved: "The server confirmed the cash action and its current balances were read back.", cashCustomerBalance: "Current customer receivable exposure", cashMfa: "The server requires stronger authentication. Complete the configured MFA flow before cash actions; password verification alone is insufficient.", cashChoose: "Choose a receipt", cashSelect: "Read receipt",
  invoiceTable: "Invoice table", tableNavigation: "Swipe or use the left/right arrow keys to see all columns. Tab moves to Review.",
  stateDraft: "Draft", stateSubmitted: "Submitted", stateApproved: "Approved", statePartiallyPaid: "Partially paid", statePaid: "Paid", stateCancelled: "Cancelled",
  title: "Receivables workspace", intro: "Prepare an invoice, send it for independent review, and follow its recorded status.",
  live: "Live · authorized API", boundary: "These actions record receivables. Inventory and general-ledger posting are separate workflows.",
  tenant: "Tenant ID", username: "Username", password: "Password", signIn: "Sign in", signOut: "Sign out / switch tenant", session: "Signed in as", workspace: "Authorized workspace", chooseWorkspace: "Choose a workspace", loading: "Loading authorized records…", refresh: "Refresh records", retry: "Retry the exact request", checking: "Check the current records before retrying. The server may already have saved your request.",
  noWorkspaces: "No workspace grant was returned for this account. Ask your administrator to grant the required scope.", noRead: "This account has no receivables permission.",
  customer: "Customer", chooseCustomer: "Choose an active customer", customers: "Existing customers", customerNote: "Select an existing customer. New customer setup is available through the existing API or CLI; this page does not overwrite customer profiles.", previous: "Previous", next: "Next", showing: "Records", of: "of", noCustomers: "No customers were returned for this page.",
  draft: "New invoice draft", number: "Invoice number", invoiceDate: "Invoice date", dueDate: "Due date", description: "Line description", quantity: "Quantity", price: "Unit price", tax: "Line tax", minorNote: "Enter whole minor units in the customer's currency.", subtotal: "Subtotal", total: "Total", minor: "minor units", save: "Save draft", invoices: "Recorded invoices", empty: "No invoices were returned for this page.", view: "Review", status: "Status", version: "Version", creator: "Created by", approver: "Approved by", outstanding: "Outstanding", submit: "Submit for review", approve: "Approve invoice", confirm: "Confirm approval", cancel: "Cancel", approvalNote: "Confirm the displayed invoice and amount. Approval requires a different authorized human and the server rechecks credit and status.", sameActor: "A different person must approve this invoice.", saved: "The server confirmed the action. The recorded document below is authoritative.", review: "Invoice review", identifier: "Record ID", due: "Due", readOnly: "Your current permissions do not allow creating invoices.",
  ar_amount_invalid: "Enter a whole nonnegative minor-unit amount no greater than 9007199254740991, including the total.", ar_quantity_invalid: "Enter a positive decimal quantity using a dot and no more than 12 digits in total.", ar_contract_invalid: "The server response cannot be represented safely by this page. No amount or success has been inferred.", failed: "The server rejected this action. Your draft is retained. Refresh to check permissions, credit, currency and the current document version before trying again.", denied: "This action is not permitted in the selected scope. Refresh your access before continuing.", unavailable: "The response could not be confirmed. No automatic retry was sent.", expired: "Your session expired or requires renewal. Sign in again; actions are never replayed automatically.", newDraft: "Start another draft", permissionChanged: "Access is checked by the server on every action.",
};
const ar: Record<keyof typeof en, string> = {
  policyUnverified: "دقة العملة التاريخية غير موثّقة. تبقى الوحدات الصغرى الأصلية ظاهرة؛ لا تتاح إجراءات مالية جديدة قبل معالجة السياسة.", policyAmountHint: "أدخل المبالغ بعملة", policyPrecision: "المنازل العشرية", policyNoRounding: "تُرفض المنازل الزائدة ولا تُقرّب.", policyEvidence: "السياسة النقدية المحفوظة", policySource: "المصدر", policyRounding: "قاعدة التقريب", policyDigest: "بصمة سجل العملات",
  ar_major_amount_invalid: "أدخل مبلغًا غير سالب بالمنازل العشرية المسجلة. استخدم النقطة أو الفاصل العشري العربي دون فواصل آلاف وضمن حد الكتابة الدقيقة.", ar_monetary_policy_unverified: "لا توجد سياسة نقدية تاريخية موثقة لهذا السجل. اقرأ وحداته الصغرى الأصلية وعالج السياسة قبل أي أثر مالي جديد.", ar_monetary_policy_mismatch: "للسجلات سياسات نقدية محفوظة مختلفة. حدّثها وعالج الاختلاف قبل توزيع الأموال.",
  newInvoice: "فاتورة جديدة", evidenceDetails: "تفاصيل الأدلة",
  cash: "المتحصلات النقدية وتوزيعها", cashIntro: "سجل مبلغًا استُلم فعليًا ثم وزّعه على هذه الفاتورة المعتمدة. تُغير هذه الإجراءات أرصدة الذمم فورًا.", cashReceipt: "إيصال تحصيل جديد", cashNumber: "رقم الإيصال", cashDate: "تاريخ الإيصال", cashAmount: "المبلغ المستلم", cashInitialAllocation: "الموزع الآن على هذه الفاتورة", cashReview: "مراجعة التحصيل", cashConfirm: "تأكيد الأثر المالي", cashReviewNote: "طابق العميل والعملة والمبالغ أدناه مع دليل السداد. يسجل الخادم الإيصال أو التوزيع فورًا.", cashAllocated: "الموزع", cashUnallocated: "رصيد الإيصال غير الموزع", cashReceipts: "إيصالات العميل المسجلة", cashSelectReceipt: "اختيار إيصال مسجل", cashAllocation: "توزيع إضافي", cashAllocateReview: "مراجعة التوزيع", cashPosted: "مسجل", cashNoReceipts: "لا يوجد إيصالات لهذا العميل في الصفحة الحالية.", cash_balance_invalid: "استخدم مبلغ تحصيل أو توزيع موجبًا. يجب ألا يتجاوز التوزيع رصيد الإيصال غير الموزع أو رصيد الفاتورة المعتمدة، وبعملة العميل نفسها.", cashRetryLimit: "بلغت المحاولات ثلاثًا. احتفظ برقم الإيصال للتحقق؛ لا تنشئ بديلاً قبل التأكد من النتيجة.", cashUnknown: "لم تتأكد النتيجة المالية. ثُبت طلب الإيصال؛ تعيد المحاولة المفتاح والقيم نفسها.", cashReadback: "تحديث الإيصال والفاتورة من الخادم", cashRecovered: "قُرئت الأرصدة المعروضة من الخادم، لكنها لا تثبت نجاح الطلب السابق بعينه. راجعها قبل إجراء مالي آخر.", cashAcknowledge: "استخدام هذه الأرصدة الحالية", cashReauth: "إعادة التحقق لإجراءات التحصيل", cashReauthNote: "يلزم تحقق بشري حديث. تمسح إعادة التحقق المسودات الخاصة؛ اختر مساحة العمل بعدها مجددًا.", cashReauthReady: "التحقق الحديث ساري. يفحصه الخادم مجددًا عند كل إجراء مالي.", cashReauthNeeded: "أعد التحقق أعلاه قبل تسجيل التحصيل أو توزيعه.", cashNew: "إعداد إيصال آخر", cashReadOnly: "تتطلب إجراءات التحصيل مستخدمًا بشريًا مخوّلاً بصلاحية إدارة الذمم.", cashInvoiceBalance: "رصيد الفاتورة الحالي", cashNoOpenInvoice: "لا يوجد رصيد معتمد مفتوح لهذه الفاتورة. تبقى الإيصالات المسجلة متاحة للمراجعة.", cashSaved: "أكد الخادم إجراء التحصيل وقُرئت أرصدته الحالية مجددًا.", cashCustomerBalance: "رصيد الذمم الحالي للعميل", cashMfa: "يتطلب الخادم تحققًا أقوى. أكمل المصادقة متعددة العوامل المضبوطة قبل إجراءات التحصيل؛ لا تكفي كلمة المرور وحدها.", cashChoose: "اختر إيصالاً", cashSelect: "قراءة الإيصال",
  invoiceTable: "جدول الفواتير", tableNavigation: "اسحب أفقيًا أو استخدم سهمَي اليمين واليسار لرؤية جميع الأعمدة. ينقلك Tab إلى المراجعة.",
  stateDraft: "مسودة", stateSubmitted: "مرسلة للمراجعة", stateApproved: "معتمدة", statePartiallyPaid: "مسددة جزئيًا", statePaid: "مسددة", stateCancelled: "ملغاة",
  title: "مساحة الذمم المدينة", intro: "أعدّ فاتورة وأرسلها لمراجعة مستقلة وتابع حالتها المسجلة.", live: "مباشر · واجهة مصرح بها", boundary: "تسجل هذه الإجراءات الذمم المدينة. المخزون والترحيل إلى الأستاذ العام مساران منفصلان.",
  tenant: "معرّف المستأجر", username: "اسم المستخدم", password: "كلمة المرور", signIn: "تسجيل الدخول", signOut: "تسجيل الخروج / تغيير المستأجر", session: "تم الدخول باسم", workspace: "مساحة العمل المصرح بها", chooseWorkspace: "اختر مساحة عمل", loading: "جارٍ تحميل السجلات المصرح بها…", refresh: "تحديث السجلات", retry: "إعادة إرسال الطلب نفسه", checking: "تحقق من السجلات الحالية قبل إعادة المحاولة؛ ربما حفظ الخادم الطلب بالفعل.",
  noWorkspaces: "لم يُرجع الحساب صلاحية لأي مساحة عمل. اطلب منح النطاق المطلوب من المسؤول.", noRead: "لا يملك هذا الحساب صلاحية للذمم المدينة.", customer: "العميل", chooseCustomer: "اختر عميلاً نشطًا", customers: "العملاء الحاليون", customerNote: "اختر عميلاً موجودًا. إعداد عميل جديد متاح عبر API أو CLI الحاليين؛ هذه الصفحة لا تستبدل ملفات العملاء.", previous: "السابق", next: "التالي", showing: "السجلات", of: "من", noCustomers: "لا يوجد عملاء في هذه الصفحة.",
  draft: "مسودة فاتورة جديدة", number: "رقم الفاتورة", invoiceDate: "تاريخ الفاتورة", dueDate: "تاريخ الاستحقاق", description: "وصف البند", quantity: "الكمية", price: "سعر الوحدة", tax: "ضريبة البند", minorNote: "أدخل عددًا صحيحًا بوحدات عملة العميل الصغرى.", subtotal: "الإجمالي قبل الضريبة", total: "الإجمالي", minor: "وحدة عملة صغرى", save: "حفظ المسودة", invoices: "الفواتير المسجلة", empty: "لا يوجد فواتير في هذه الصفحة.", view: "مراجعة", status: "الحالة", version: "الإصدار", creator: "أنشأها", approver: "اعتمدها", outstanding: "المتبقي", submit: "إرسال للمراجعة", approve: "اعتماد الفاتورة", confirm: "تأكيد الاعتماد", cancel: "إلغاء", approvalNote: "أكد الفاتورة والمبلغ المعروضين. يلزم شخص آخر مخوّل، ويعيد الخادم التحقق من الائتمان والحالة.", sameActor: "يجب أن يعتمد هذه الفاتورة شخص آخر.", saved: "أكد الخادم الإجراء. المستند المسجل أدناه هو المرجع.", review: "مراجعة الفاتورة", identifier: "معرّف السجل", due: "الاستحقاق", readOnly: "صلاحياتك الحالية لا تتيح إنشاء فواتير.",
  ar_amount_invalid: "أدخل مبلغًا صحيحًا غير سالب بوحدات العملة الصغرى لا يتجاوز 9007199254740991، بما في ذلك الإجمالي.", ar_quantity_invalid: "أدخل كمية عشرية موجبة باستخدام النقطة وبحد أقصى 12 رقمًا إجمالاً.", ar_contract_invalid: "لا تستطيع هذه الصفحة تمثيل رد الخادم بدقة. لم يُفترض أي مبلغ أو نجاح.", failed: "رفض الخادم الإجراء. احتُفظ بالمسودة. حدّث السجلات للتحقق من الصلاحيات والائتمان والعملة وإصدار المستند قبل المحاولة مجددًا.", denied: "هذا الإجراء غير مسموح في النطاق المختار. حدّث صلاحياتك قبل المتابعة.", unavailable: "تعذر تأكيد الرد. لم تُرسل إعادة محاولة تلقائية.", expired: "انتهت الجلسة أو يلزم تجديدها. سجّل الدخول مجددًا؛ لن تعاد الإجراءات تلقائيًا.", newDraft: "بدء مسودة أخرى", permissionChanged: "يتحقق الخادم من الصلاحيات عند كل إجراء.",
};
export type ArMessage = keyof typeof en;
export const arTranslate = (locale: Locale, key: ArMessage): string => (locale === "ar" ? ar : en)[key];
