import type { Locale } from "./types";

const en = {
  invoiceTable: "Invoice table", tableNavigation: "Swipe or use the left/right arrow keys to see all columns. Tab moves to Review.",
  stateDraft: "Draft", stateSubmitted: "Submitted", stateApproved: "Approved", statePartiallyPaid: "Partially paid", statePaid: "Paid", stateCancelled: "Cancelled",
  title: "Receivables workspace", intro: "Prepare an invoice, send it for independent review, and follow its recorded status.",
  live: "Live · authorized API", boundary: "These actions record receivables. Inventory and general-ledger posting are separate workflows.",
  tenant: "Tenant ID", username: "Username", password: "Password", signIn: "Sign in", signOut: "Sign out / switch tenant", session: "Signed in as", workspace: "Authorized workspace", chooseWorkspace: "Choose a workspace", loading: "Loading authorized records…", refresh: "Refresh records", retry: "Retry the exact request", checking: "Check the current records before retrying. The server may already have saved your request.",
  noWorkspaces: "No workspace grant was returned for this account. Ask your administrator to grant the required scope.", noRead: "This account has no receivables permission.",
  customer: "Customer", chooseCustomer: "Choose an active customer", customers: "Existing customers", customerNote: "Select an existing customer. New customer setup is available through the existing API or CLI; this page does not overwrite customer profiles.", previous: "Previous", next: "Next", showing: "Records", of: "of", noCustomers: "No customers were returned for this page.",
  draft: "New invoice draft", number: "Invoice number", invoiceDate: "Invoice date", dueDate: "Due date", description: "Line description", quantity: "Quantity", price: "Unit price · minor units", tax: "Line tax · minor units", minorNote: "Enter integer minor units in the customer's currency. No decimal currency conversion is applied. Maximum amount: 9007199254740991; quantity: up to 12 digits in total.", subtotal: "Subtotal", total: "Total", minor: "minor units", save: "Save draft", invoices: "Recorded invoices", empty: "No invoices were returned for this page.", view: "Review", status: "Status", version: "Version", creator: "Created by", approver: "Approved by", outstanding: "Outstanding", submit: "Submit for review", approve: "Approve invoice", confirm: "Confirm approval", cancel: "Cancel", approvalNote: "Confirm the displayed invoice and amount. Approval requires a different authorized human and the server rechecks credit and status.", sameActor: "A different person must approve this invoice.", saved: "The server confirmed the action. The recorded document below is authoritative.", review: "Invoice review", identifier: "Record ID", due: "Due", readOnly: "Your current permissions do not allow creating invoices.",
  ar_amount_invalid: "Enter a whole nonnegative minor-unit amount within the displayed limit. The total must also fit that limit.", ar_quantity_invalid: "Enter a positive decimal quantity using a dot and no more than 12 digits in total.", ar_contract_invalid: "The server response cannot be represented safely by this page. No amount or success has been inferred.", failed: "The server rejected this action. Your draft is retained. Refresh to check permissions, credit, currency and the current document version before trying again.", denied: "This action is not permitted in the selected scope. Refresh your access before continuing.", unavailable: "The response could not be confirmed. No automatic retry was sent.", expired: "Your session expired or requires renewal. Sign in again; actions are never replayed automatically.", newDraft: "Start another draft", permissionChanged: "Access is checked by the server on every action.",
};
const ar: Record<keyof typeof en, string> = {
  invoiceTable: "جدول الفواتير", tableNavigation: "اسحب أفقيًا أو استخدم سهمَي اليمين واليسار لرؤية جميع الأعمدة. ينقلك Tab إلى المراجعة.",
  stateDraft: "مسودة", stateSubmitted: "مرسلة للمراجعة", stateApproved: "معتمدة", statePartiallyPaid: "مسددة جزئيًا", statePaid: "مسددة", stateCancelled: "ملغاة",
  title: "مساحة الذمم المدينة", intro: "أعدّ فاتورة وأرسلها لمراجعة مستقلة وتابع حالتها المسجلة.", live: "مباشر · واجهة مصرح بها", boundary: "تسجل هذه الإجراءات الذمم المدينة. المخزون والترحيل إلى الأستاذ العام مساران منفصلان.",
  tenant: "معرّف المستأجر", username: "اسم المستخدم", password: "كلمة المرور", signIn: "تسجيل الدخول", signOut: "تسجيل الخروج / تغيير المستأجر", session: "تم الدخول باسم", workspace: "مساحة العمل المصرح بها", chooseWorkspace: "اختر مساحة عمل", loading: "جارٍ تحميل السجلات المصرح بها…", refresh: "تحديث السجلات", retry: "إعادة إرسال الطلب نفسه", checking: "تحقق من السجلات الحالية قبل إعادة المحاولة؛ ربما حفظ الخادم الطلب بالفعل.",
  noWorkspaces: "لم يُرجع الحساب صلاحية لأي مساحة عمل. اطلب منح النطاق المطلوب من المسؤول.", noRead: "لا يملك هذا الحساب صلاحية للذمم المدينة.", customer: "العميل", chooseCustomer: "اختر عميلاً نشطًا", customers: "العملاء الحاليون", customerNote: "اختر عميلاً موجودًا. إعداد عميل جديد متاح عبر API أو CLI الحاليين؛ هذه الصفحة لا تستبدل ملفات العملاء.", previous: "السابق", next: "التالي", showing: "السجلات", of: "من", noCustomers: "لا يوجد عملاء في هذه الصفحة.",
  draft: "مسودة فاتورة جديدة", number: "رقم الفاتورة", invoiceDate: "تاريخ الفاتورة", dueDate: "تاريخ الاستحقاق", description: "وصف البند", quantity: "الكمية", price: "سعر الوحدة · وحدات العملة الصغرى", tax: "ضريبة البند · وحدات العملة الصغرى", minorNote: "أدخل عددًا صحيحًا بوحدات عملة العميل الصغرى دون تحويل عشري للعملة. الحد الأقصى للمبلغ: 9007199254740991؛ الكمية: 12 رقمًا إجمالاً.", subtotal: "الإجمالي قبل الضريبة", total: "الإجمالي", minor: "وحدة عملة صغرى", save: "حفظ المسودة", invoices: "الفواتير المسجلة", empty: "لا يوجد فواتير في هذه الصفحة.", view: "مراجعة", status: "الحالة", version: "الإصدار", creator: "أنشأها", approver: "اعتمدها", outstanding: "المتبقي", submit: "إرسال للمراجعة", approve: "اعتماد الفاتورة", confirm: "تأكيد الاعتماد", cancel: "إلغاء", approvalNote: "أكد الفاتورة والمبلغ المعروضين. يلزم شخص آخر مخوّل، ويعيد الخادم التحقق من الائتمان والحالة.", sameActor: "يجب أن يعتمد هذه الفاتورة شخص آخر.", saved: "أكد الخادم الإجراء. المستند المسجل أدناه هو المرجع.", review: "مراجعة الفاتورة", identifier: "معرّف السجل", due: "الاستحقاق", readOnly: "صلاحياتك الحالية لا تتيح إنشاء فواتير.",
  ar_amount_invalid: "أدخل مبلغًا صحيحًا غير سالب بوحدات العملة الصغرى ضمن الحد المعروض؛ يجب أن يكون الإجمالي ضمن الحد أيضًا.", ar_quantity_invalid: "أدخل كمية عشرية موجبة باستخدام النقطة وبحد أقصى 12 رقمًا إجمالاً.", ar_contract_invalid: "لا تستطيع هذه الصفحة تمثيل رد الخادم بدقة. لم يُفترض أي مبلغ أو نجاح.", failed: "رفض الخادم الإجراء. احتُفظ بالمسودة. حدّث السجلات للتحقق من الصلاحيات والائتمان والعملة وإصدار المستند قبل المحاولة مجددًا.", denied: "هذا الإجراء غير مسموح في النطاق المختار. حدّث صلاحياتك قبل المتابعة.", unavailable: "تعذر تأكيد الرد. لم تُرسل إعادة محاولة تلقائية.", expired: "انتهت الجلسة أو يلزم تجديدها. سجّل الدخول مجددًا؛ لن تعاد الإجراءات تلقائيًا.", newDraft: "بدء مسودة أخرى", permissionChanged: "يتحقق الخادم من الصلاحيات عند كل إجراء.",
};
export type ArMessage = keyof typeof en;
export const arTranslate = (locale: Locale, key: ArMessage): string => (locale === "ar" ? ar : en)[key];
