import type { Locale } from "./types";
const en = {
 title: "Sales & revenue", intro: "Quotations, completed services, governed invoices and collections in one selected entity.",
 signIn: "Sign in", signOut: "Sign out", tenant: "Tenant", username: "Username", password: "Password", stepUp: "Reauthenticate", scope: "Business scope", workspace: "Workspace", organization: "Organization", entity: "Legal entity", load: "Load sales", refresh: "Refresh", next: "Next page", first: "First page",
 create: "Create quotation", number: "Quotation number", customer: "Customer", date: "Business date", valid: "Valid until", currency: "Currency", description: "Service description", quantity: "Quantity", unit: "Unit price (minor units)", discount: "Discount (basis points)", add: "Add service", remove: "Remove service", open: "Open", empty: "No sales in this entity.", reason: "Decision reason", reference: "Customer order / completion reference", submit: "Submit for approval", approve: "Approve quotation", order: "Confirm customer order", fulfill: "Record service completion", cancel: "Cancel unfulfilled order", invoice: "Prepare invoice", invoiceNumber: "Invoice number", due: "Due date", journal: "Journal", period: "Fiscal period", ar: "Receivable account", revenue: "Revenue account", reviewInvoice: "Review invoice & GL", postInvoice: "Post revenue", collection: "Prepare full collection", receipt: "Receipt number", cash: "Cash account", reviewCollection: "Review collection", postCollection: "Post collection & GL", events: "Decision history", outstanding: "Outstanding", evidence: "Financial evidence", retry: "Retry the same command", unknown: "The command outcome is unknown. Retry the retained command before making another change.", failed: "The operation was rejected. Refresh current state and authority before continuing.", missing: "Sign in and select your authorized workspace, organization and entity.", denied: "Current permissions or scope do not allow this operation.", stepRequired: "Recent human reauthentication is required for write operations.", stockBoundary: "This workflow records completed services. Stock delivery, taxes and credit notes require their supported workflows.", loading: "Loading…", customerFoundation: "Customers & credit", name: "Customer name", creditLimit: "Credit limit (minor units)", terms: "Payment terms (days)", saveCustomer: "Save customer", customerCode: "Customer code", loadingCustomers: "Load active customers", invalid: "Enter exact amounts, valid dates and all required fields.",
 Draft: "Draft quotation", Submitted: "Awaiting quotation approval", Approved: "Approved quotation", Ordered: "Confirmed order", Fulfilled: "Service completed", InvoicePrepared: "Invoice awaits review", InvoiceReviewed: "Invoice reviewed", Invoiced: "Revenue posted", CollectionPrepared: "Collection awaits review", CollectionReviewed: "Collection reviewed", Paid: "Collected", Cancelled: "Cancelled",
};
export type SalesMessage = keyof typeof en;
const ar: Record<SalesMessage, string> = {
 title: "المبيعات والإيرادات", intro: "عروض الأسعار والخدمات المنجزة والفواتير والتحصيلات المعتمدة داخل كيان محدد.", signIn: "تسجيل الدخول", signOut: "تسجيل الخروج", tenant: "المستأجر", username: "اسم المستخدم", password: "كلمة المرور", stepUp: "إعادة التحقق", scope: "نطاق العمل", workspace: "مساحة العمل", organization: "المؤسسة", entity: "الكيان القانوني", load: "تحميل المبيعات", refresh: "تحديث", next: "الصفحة التالية", first: "الصفحة الأولى", create: "إنشاء عرض سعر", number: "رقم عرض السعر", customer: "العميل", date: "تاريخ العملية", valid: "صالح حتى", currency: "العملة", description: "وصف الخدمة", quantity: "الكمية", unit: "سعر الوحدة بالوحدات النقدية الصغرى", discount: "الخصم بنقاط الأساس", add: "إضافة خدمة", remove: "حذف خدمة", open: "فتح", empty: "لا توجد مبيعات في هذا الكيان.", reason: "سبب القرار", reference: "مرجع طلب العميل أو إنجاز الخدمة", submit: "تقديم للاعتماد", approve: "اعتماد عرض السعر", order: "تأكيد طلب العميل", fulfill: "تسجيل إنجاز الخدمة", cancel: "إلغاء الطلب غير المنجز", invoice: "إعداد الفاتورة", invoiceNumber: "رقم الفاتورة", due: "تاريخ الاستحقاق", journal: "دفتر اليومية", period: "الفترة المالية", ar: "حساب العملاء", revenue: "حساب الإيرادات", reviewInvoice: "مراجعة الفاتورة والقيد", postInvoice: "ترحيل الإيراد", collection: "إعداد التحصيل الكامل", receipt: "رقم إيصال التحصيل", cash: "حساب النقدية", reviewCollection: "مراجعة التحصيل", postCollection: "ترحيل التحصيل والقيد", events: "سجل القرارات", outstanding: "الرصيد المستحق", evidence: "الأدلة المالية", retry: "إعادة إرسال الأمر نفسه", unknown: "نتيجة الأمر غير مؤكدة. أعد إرسال الأمر المحفوظ قبل إجراء تعديل آخر.", failed: "رُفضت العملية. حدّث الحالة والصلاحيات قبل المتابعة.", missing: "سجّل الدخول واختر مساحة العمل والمؤسسة والكيان المصرح بها.", denied: "الصلاحيات أو النطاق الحالي لا يسمحان بهذه العملية.", stepRequired: "يلزم تحقق بشري حديث لتنفيذ عمليات الكتابة.", stockBoundary: "هذا المسار يسجل الخدمات المنجزة. تسليم المخزون والضرائب والإشعارات الائتمانية تتطلب مساراتها المدعومة.", loading: "جارٍ التحميل…", customerFoundation: "العملاء والائتمان", name: "اسم العميل", creditLimit: "حد الائتمان بالوحدات النقدية الصغرى", terms: "مدة السداد بالأيام", saveCustomer: "حفظ العميل", customerCode: "رمز العميل", loadingCustomers: "تحميل العملاء النشطين", invalid: "أدخل مبالغ دقيقة وتواريخ صحيحة وجميع الحقول المطلوبة.", Draft: "عرض سعر مسودة", Submitted: "بانتظار اعتماد العرض", Approved: "عرض معتمد", Ordered: "طلب مؤكد", Fulfilled: "خدمة منجزة", InvoicePrepared: "فاتورة بانتظار المراجعة", InvoiceReviewed: "فاتورة مراجعة", Invoiced: "إيراد مرحّل", CollectionPrepared: "تحصيل بانتظار المراجعة", CollectionReviewed: "تحصيل مراجَع", Paid: "مُحصّل", Cancelled: "ملغي",
};
export function salesTranslate(locale: Locale, key: SalesMessage): string { return (locale === "ar" ? ar : en)[key]; }
