import type { Locale } from "./types";
const en = {
  title: "Product sales", intro: "Reserve physical stock, review exact FIFO cost, deliver and collect through the financial ledger.", cancelReview: "Review the retained COGS draft independently before cancelling its unposted financial plan.",
  boundary: "One non-lot item, full delivery and full collection in functional currency. Tax is explicitly zero; partial shipments, returns and credit notes are outside this cycle.",
  tenant: "Tenant", username: "Username", password: "Password", signIn: "Sign in", signOut: "Sign out", stepUp: "Verify for financial actions", stepRequired: "Verify your password before financial changes.",
  scope: "Working scope", workspace: "Workspace", organization: "Organization", entity: "Legal entity", load: "Load selected scope", refresh: "Refresh", loading: "Loading authorized data…", denied: "Current authority does not permit this action. Reload your identity and scope.",
  failed: "The operation was refused. Refresh the source before submitting another command.", invalid: "Check the required exact values and selected master data.", unknown: "The acknowledgement is unknown. Retry the original frozen request before editing or changing scope.", retry: "Retry original request", nameHint: "Numbers accept up to64 ASCII letters, digits, hyphen, underscore or dot.",
  empty: "No product sales in this selected scope.", open: "Open", create: "Create product order", number: "Order number", customer: "Customer", reference: "Customer reference", item: "Stock item", warehouse: "Warehouse", location: "Stock location", quantity: "Quantity", unit: "Unit price in minor units", discount: "Discount in basis points", date: "Business date", description: "Description", currency: "Currency", reason: "Decision reason", total: "Sales value", cost: "FIFO COGS", policy: "FIFO policy", period: "Accounting period", journal: "Journal", invoiceNumber: "Invoice number", due: "Due date", ar: "Receivable account", revenue: "Revenue account", cash: "Cash account", receipt: "Cash receipt number", evidence: "Native financial evidence", events: "Audit history", listBound: "This view displays up to100 orders in the selected scope.",
  submit: "Submit order", approve: "Approve customer terms", reserve: "Reserve stock", prepareIssue: "Prepare FIFO issue", reviewIssue: "Review FIFO and COGS", deliver: "Deliver and post COGS", prepareInvoice: "Prepare AR invoice", reviewInvoice: "Review revenue", postInvoice: "Post revenue", prepareCollection: "Prepare full collection", reviewCollection: "Review collection", collect: "Collect and post cash", cancel: "Cancel before delivery",
  Draft: "Draft", Submitted: "Submitted", Approved: "Approved", Reserved: "Reserved", IssuePrepared: "FIFO prepared", IssueReviewed: "FIFO reviewed", Delivered: "Delivered", InvoicePrepared: "Invoice prepared", InvoiceReviewed: "Revenue reviewed", Invoiced: "Invoiced", CollectionPrepared: "Collection prepared", CollectionReviewed: "Collection reviewed", Paid: "Paid", Cancelled: "Cancelled",
} as const;
const ar: Record<keyof typeof en, string> = {
  title: "مبيعات المنتجات", intro: "احجز المخزون الفعلي وراجع تكلفة FIFO الدقيقة ثم سلّم وحصّل مع الأثر المالي في دفتر الأستاذ.", cancelReview: "راجع مسودة التكلفة بشكل مستقل قبل إلغاء خطتها المالية غير المرحلة.",
  boundary: "صنف واحد دون تتبع دفعات، وتسليم وتحصيل كامل بالعملة الوظيفية. الضريبة صفر صراحةً؛ الشحنات الجزئية والمرتجعات والإشعارات الدائنة خارج هذه الدورة.",
  tenant: "المستأجر", username: "اسم المستخدم", password: "كلمة المرور", signIn: "تسجيل الدخول", signOut: "تسجيل الخروج", stepUp: "التحقق لتنفيذ العمليات المالية", stepRequired: "تحقق من كلمة المرور قبل التغييرات المالية.",
  scope: "نطاق العمل", workspace: "مساحة العمل", organization: "المنظمة", entity: "الكيان القانوني", load: "تحميل النطاق المحدد", refresh: "تحديث", loading: "جارٍ تحميل البيانات المصرح بها…", denied: "الصلاحيات الحالية لا تسمح بالعملية. أعد تحميل الهوية والنطاق.",
  failed: "رُفضت العملية. حدّث المصدر قبل إرسال أمر آخر.", invalid: "راجع القيم الدقيقة المطلوبة والبيانات الأساسية المحددة.", unknown: "نتيجة الإقرار غير معروفة. أعد الطلب الأصلي المحفوظ قبل تعديل البيانات أو تغيير النطاق.", retry: "إعادة الطلب الأصلي", nameHint: "الأرقام تقبل حتى64 حرفًا لاتينيًا أو رقمًا أو شرطة أو شرطة سفلية أو نقطة.",
  empty: "لا توجد مبيعات منتجات في النطاق المحدد.", open: "فتح", create: "إنشاء طلب منتجات", number: "رقم الطلب", customer: "العميل", reference: "مرجع العميل", item: "صنف المخزون", warehouse: "المستودع", location: "موقع المخزون", quantity: "الكمية", unit: "سعر الوحدة بالوحدات النقدية الصغرى", discount: "الخصم بنقاط الأساس", date: "تاريخ العملية", description: "الوصف", currency: "العملة", reason: "سبب القرار", total: "قيمة المبيعات", cost: "تكلفة البضاعة المباعة FIFO", policy: "سياسة FIFO", period: "الفترة المحاسبية", journal: "اليومية", invoiceNumber: "رقم الفاتورة", due: "تاريخ الاستحقاق", ar: "حساب العملاء", revenue: "حساب الإيراد", cash: "حساب النقدية", receipt: "رقم إيصال التحصيل", evidence: "الأدلة المالية الأصلية", events: "سجل التدقيق", listBound: "تعرض هذه الصفحة حتى100 طلب في النطاق المحدد.",
  submit: "إرسال الطلب", approve: "اعتماد شروط العميل", reserve: "حجز المخزون", prepareIssue: "إعداد صرف FIFO", reviewIssue: "مراجعة FIFO والتكلفة", deliver: "التسليم وترحيل التكلفة", prepareInvoice: "إعداد فاتورة العملاء", reviewInvoice: "مراجعة الإيراد", postInvoice: "ترحيل الإيراد", prepareCollection: "إعداد التحصيل الكامل", reviewCollection: "مراجعة التحصيل", collect: "التحصيل وترحيل النقدية", cancel: "الإلغاء قبل التسليم",
  Draft: "مسودة", Submitted: "مرسل", Approved: "معتمد", Reserved: "محجوز", IssuePrepared: "صرف FIFO مُعد", IssueReviewed: "صرف FIFO مُراجع", Delivered: "مسلّم", InvoicePrepared: "فاتورة مُعدة", InvoiceReviewed: "إيراد مُراجع", Invoiced: "مفوتر", CollectionPrepared: "تحصيل مُعد", CollectionReviewed: "تحصيل مُراجع", Paid: "مدفوع", Cancelled: "ملغى",
};
export type StockMessage = keyof typeof en;
export const stockTranslate = (locale: Locale, key: StockMessage): string => (locale === "ar" ? ar : en)[key];
