import { CheckCircle2 } from "lucide-react";
import { useState } from "react";

import { applyAdminRetentionPolicy, createAdminRetentionPolicy, disableAdminIntegration, updateAdminRetentionPolicy } from "../data";
import type { MessageKey } from "../i18n";
import type { AdminIntegration, AdminRetentionPolicy, BrowserAdminSession } from "../types";

type Action = "apply" | "create" | "disable" | "edit" | "reactivate" | "retire";

export function AdminGovernanceMutations({ session, integrations, policies, translate, refresh, onError }: { session: BrowserAdminSession; integrations: AdminIntegration[]; policies: AdminRetentionPolicy[]; translate: (key: MessageKey) => string; refresh: () => Promise<void>; onError: (error: unknown) => void; }) {
  const [action, setAction] = useState<Action | null>(null); const [integration, setIntegration] = useState<AdminIntegration | null>(null); const [policy, setPolicy] = useState<AdminRetentionPolicy | null>(null);
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [classification, setClassification] = useState<AdminRetentionPolicy["dataClassification"]>("internal"); const [days, setDays] = useState(365); const [evidenceId, setEvidenceId] = useState(""); const [retentionVersion, setRetentionVersion] = useState(1); const [confirmation, setConfirmation] = useState(""); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<MessageKey | null>(null);
  const expected = action === "disable" ? "DISABLE" : action === "create" ? "CREATE" : action === "retire" ? "RETIRE" : action === "reactivate" ? "REACTIVATE" : "APPLY";
  const begin = (next: Action, selectedPolicy?: AdminRetentionPolicy, selectedIntegration?: AdminIntegration) => { setAction(next); setPolicy(selectedPolicy ?? null); setIntegration(selectedIntegration ?? null); setConfirmation(""); setNotice(null); if (next === "create") { setName(""); setDescription(""); setClassification("internal"); setDays(365); } if (next === "edit" && selectedPolicy) { setDescription(selectedPolicy.description); setClassification(selectedPolicy.dataClassification); setDays(selectedPolicy.durationDays); } if (next === "apply") { setEvidenceId(""); setRetentionVersion(1); } };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!action || confirmation.trim() !== expected) return; setBusy(true); setNotice(null); try { if (action === "disable" && integration) { const result = await disableAdminIntegration(session, integration, "security_response"); setNotice(result.transitioned ? "adminGovernanceIntegrationDisabled" : "adminGovernanceNoChange"); } else if (action === "create") { const result = await createAdminRetentionPolicy(session, { name, description, dataClassification: classification, durationDays: days }); setNotice(result.transitioned ? "adminGovernancePolicyCreated" : "adminGovernanceNoChange"); } else if (action === "edit" && policy) { const result = await updateAdminRetentionPolicy(session, policy, { description, dataClassification: classification, durationDays: days }); setNotice(result.transitioned ? "adminGovernancePolicyUpdated" : "adminGovernanceNoChange"); } else if ((action === "retire" || action === "reactivate") && policy) { const result = await updateAdminRetentionPolicy(session, policy, { active: action === "reactivate" }); setNotice(result.transitioned ? (action === "retire" ? "adminGovernancePolicyRetired" : "adminGovernancePolicyReactivated") : "adminGovernanceNoChange"); } else if (action === "apply" && policy) { const result = await applyAdminRetentionPolicy(session, policy, evidenceId, retentionVersion); setNotice(result.retentionExtended ? "adminGovernanceRetentionExtended" : "adminGovernanceRetentionPreserved"); } else return; await refresh(); setAction(null); setEvidenceId(""); setConfirmation(""); } catch (error) { onError(error); } finally { setBusy(false); } };
  return <>
    {notice ? <p className="admin-security-status" role="status"><CheckCircle2 size={16} aria-hidden="true" />{translate(notice)}</p> : null}
    <button className="primary-button" disabled={busy} onClick={() => begin("create")}>{translate("adminGovernanceCreatePolicy")}</button>
    <div className="table-scroll"><table className="live-table"><caption>{translate("adminGovernanceIntegrations")}</caption><thead><tr><th>{translate("adminGovernanceKind")}</th><th>{translate("adminIdentityStatus")}</th><th>{translate("adminGovernanceCredentials")}</th><th>{translate("adminIdentityAction")}</th></tr></thead><tbody>{integrations.map((item) => <tr key={`${item.kind}:${item.id}`}><th scope="row">{item.kind}</th><td>{item.status}</td><td>{item.activeCredentialCount}/{item.credentialCount}</td><td>{item.status === "active" ? <button className="danger-button" disabled={busy} onClick={() => begin("disable", undefined, item)}>{translate("adminGovernanceDisable")}</button> : translate("adminIdentityNoAction")}</td></tr>)}</tbody></table></div>
    <div className="table-scroll"><table className="live-table"><caption>{translate("adminGovernanceRetention")}</caption><thead><tr><th>{translate("adminAccessRole")}</th><th>{translate("adminGovernanceClassification")}</th><th>{translate("adminGovernanceDuration")}</th><th>{translate("adminIdentityStatus")}</th><th>{translate("adminIdentityAction")}</th></tr></thead><tbody>{policies.map((item) => <tr key={item.id}><th scope="row"><strong>{item.name}</strong><small>{item.description}</small></th><td>{item.dataClassification}</td><td>{item.durationDays}</td><td>{item.active ? translate("adminIdentityActive") : translate("adminAccessRetired")}</td><td><div className="admin-table-actions">{item.active ? <><button className="secondary-button" disabled={busy} onClick={() => begin("edit", item)}>{translate("adminGovernanceEdit")}</button><button className="secondary-button" disabled={busy} onClick={() => begin("apply", item)}>{translate("adminGovernanceApply")}</button><button className="danger-button" disabled={busy} onClick={() => begin("retire", item)}>{translate("adminGovernanceRetire")}</button></> : <button className="secondary-button" disabled={busy} onClick={() => begin("reactivate", item)}>{translate("adminGovernanceReactivate")}</button>}</div></td></tr>)}</tbody></table></div>
    {action ? <form className="admin-form admin-access-action" onSubmit={submit}><h3>{translate("adminGovernanceChangeTitle")}</h3>{action === "create" ? <label>{translate("adminGovernancePolicyName")}<input required maxLength={64} value={name} onChange={(event) => setName(event.target.value)} /></label> : null}{action === "create" || action === "edit" ? <><label>{translate("adminAccessDescription")}<textarea maxLength={500} value={description} onChange={(event) => setDescription(event.target.value)} /></label><label>{translate("adminGovernanceClassification")}<select value={classification} onChange={(event) => setClassification(event.target.value as AdminRetentionPolicy["dataClassification"])}>{["public", "internal", "confidential", "restricted"].map((value) => <option key={value}>{value}</option>)}</select></label><label>{translate("adminGovernanceDuration")}<input required type="number" min={1} max={36500} value={days} onChange={(event) => setDays(event.currentTarget.valueAsNumber)} /></label></> : null}{action === "apply" ? <><label>{translate("adminGovernanceEvidenceId")}<input required value={evidenceId} onChange={(event) => setEvidenceId(event.target.value)} autoComplete="off" /></label><label>{translate("adminGovernanceRetentionVersion")}<input required type="number" min={1} value={retentionVersion} onChange={(event) => setRetentionVersion(event.currentTarget.valueAsNumber)} /></label></> : null}<label>{translate("adminAccessTypeConfirmation")} <strong>{expected}</strong><input required value={confirmation} onChange={(event) => setConfirmation(event.target.value)} autoComplete="off" placeholder={expected} /></label><p>{translate("adminGovernanceMutationWarning")}</p><div className="admin-action-row"><button className={action === "disable" || action === "retire" ? "danger-button" : "primary-button"} disabled={busy || confirmation.trim() !== expected}>{translate("adminAccessConfirmChange")}</button><button type="button" className="secondary-button" disabled={busy} onClick={() => { setAction(null); setEvidenceId(""); }}>{translate("adminIdentityCancel")}</button></div></form> : null}
  </>;
}
