import { useEffect, useRef, useState, type FormEvent } from "react";
import { useBrowserSession } from "../browserSession";
import { receiptMoney, receiptRequest, type ReceiptScope, type ReceiptView } from "../inventory-receipt-data";
import type { Locale } from "../types";
const labels = {
 en: { title: "Reviewed inventory receipt posting", intro: "Prepare a receipt, independently review its exact stock and journal plan, then commit the complete stock, FIFO value and general ledger effect. Corrections require a reviewed full reversal of an entirely unused receipt.", signIn: "Sign in and reauthenticate in Identity Administration before posting.", scope: "Authorized scope", workspace: "Workspace ID", organization: "Organization ID", entity: "Legal entity ID", prepare: "Prepare receipt", number: "Receipt number", date: "Posting date", period: "Fiscal period ID", item: "Item code", location: "Warehouse/location code", quantity: "Exact quantity", value: "Total value in minor units", policy: "FIFO policy code", orgCode: "Organization code", entityCode: "Entity code", reason: "Reason", load: "Recover retained receipt", planId: "Plan ID", review: "Review exact plan", commit: "Commit reviewed stock and GL", reversal: "Prepare full unused reversal", reversalNumber: "Reversal number", command: "Command ID", retry: "Retry identical command", evidence: "Retained evidence", account: "Account", debit: "Debit", credit: "Credit", prepared: "Prepared", reviewed: "Reviewed", committed: "Committed", busy: "Working…", error: "Command failed; recover current state or retry the identical command.", pending: "An acknowledgement is uncertain. Retry the identical command before preparing another command.", authority: "Actions require current permissions, recent reauthentication and a reviewer distinct from the preparer.", source: "Source", reviewEvidence: "Review", effect: "Complete effect" },
 ar: { title: "ترحيل استلام مخزون بعد مراجعة مستقلة", intro: "جهّز الاستلام ثم راجع خطة المخزون والقيد الدقيقة بهوية مستقلة، ثم رحّل المخزون وتكلفة FIFO والأستاذ العام في عملية واحدة. التصحيح يتطلب عكسًا كاملاً بعد مراجعة الاستلام غير المستخدم بالكامل.", signIn: "سجّل الدخول وأعد التحقق من هويتك في إدارة الهوية قبل الترحيل.", scope: "نطاق الصلاحية", workspace: "معرّف مساحة العمل", organization: "معرّف المنظمة", entity: "معرّف الكيان القانوني", prepare: "تجهيز الاستلام", number: "رقم الاستلام", date: "تاريخ الترحيل", period: "معرّف الفترة المالية", item: "رمز الصنف", location: "رمز المستودع/الموقع", quantity: "الكمية الدقيقة", value: "القيمة بالوحدات النقدية الصغرى", policy: "رمز سياسة FIFO", orgCode: "رمز المنظمة", entityCode: "رمز الكيان", reason: "السبب", load: "استعادة الاستلام المحفوظ", planId: "معرّف الخطة", review: "مراجعة الخطة الدقيقة", commit: "ترحيل المخزون والأستاذ العام", reversal: "تجهيز عكس كامل غير مستخدم", reversalNumber: "رقم العكس", command: "معرّف الأمر", retry: "إعادة الأمر نفسه", evidence: "الأدلة المحفوظة", account: "الحساب", debit: "مدين", credit: "دائن", prepared: "مجهز", reviewed: "مراجع", committed: "مرحل", busy: "جارٍ التنفيذ…", error: "تعذر الأمر؛ استعد الحالة الحالية أو أعد الأمر نفسه.", pending: "نتيجة الأمر غير مؤكدة. أعد الأمر نفسه قبل تجهيز أمر آخر.", authority: "تتطلب الإجراءات صلاحيات حالية وإعادة تحقق حديثة ومراجعًا مختلفًا عن المُجهّز.", source: "المصدر", reviewEvidence: "المراجعة", effect: "الأثر الكامل" }
};
const empty = { receipt_number: "", posting_date: "", period_id: "", item_code: "", location_code: "", quantity: "", total_value_minor: "", policy_code: "", organization_code: "", entity_code: "", reason: "" };
export function InventoryReceiptPosting({ locale = "en" }: { locale?: Locale }) {
 const t = labels[locale], auth = useBrowserSession();
 const [scope, setScope] = useState<ReceiptScope>({ workspace: "", organization: "", entity: "" });
 const [fields, setFields] = useState(empty), [planId, setPlanId] = useState(""), [view, setView] = useState<ReceiptView | null>(null);
 const [reason, setReason] = useState(""), [reversalNumber, setReversalNumber] = useState(""), [reversalDate, setReversalDate] = useState(""), [reversalPeriod, setReversalPeriod] = useState("");
 const [busy, setBusy] = useState(false), [error, setError] = useState("");
 const [pending, setPending] = useState<{ suffix: string; body: Record<string, string>; scope: ReceiptScope } | null>(null);
 const epoch = useRef(0), inflight = useRef(false);
 useEffect(() => { epoch.current++; setView(null); setError(""); setPending(null); }, [auth.revision, scope.workspace, scope.organization, scope.entity]);
 async function run(suffix: string, body?: Record<string, string>, retryScope = scope) {
  if (!auth.session || inflight.current) return;
  const revision = auth.revision, generation = epoch.current; inflight.current = true; setBusy(true); setError("");
  if (body) setPending({ suffix, body, scope: { ...retryScope } });
  try { const result = await receiptRequest(auth.session, retryScope, suffix, body); if (generation !== epoch.current || !auth.isCurrent(revision)) return; setView(result); setPlanId(result.plan_id); if (body) setPending(null); }
  catch (e) { if (generation !== epoch.current || !auth.isCurrent(revision)) return; auth.recover(e, revision); setError(e instanceof Error ? e.message : t.error); }
  finally { inflight.current = false; setBusy(false); }
 }
 const command = () => crypto.randomUUID();
 function prepare(event: FormEvent) { event.preventDefault(); if (pending) return; void run("/plans", { ...fields, workspace: scope.workspace, command_id: command() }); }
 const field = (key: keyof typeof empty, label: string) => <label key={key}>{label}<input required value={fields[key]} type={key === "posting_date" ? "date" : "text"} inputMode={["quantity", "total_value_minor"].includes(key) ? "decimal" : undefined} onChange={e => setFields(v => ({ ...v, [key]: e.target.value }))} /></label>;
 return <main className="workbench-content" id="main-content" dir={locale === "ar" ? "rtl" : "ltr"}>
  <header className="workbench-hero"><div><h1>{t.title}</h1><p>{t.intro}</p></div></header>
  {!auth.session && <p role="status">{t.signIn}</p>}
  <section className="panel workbench-panel"><h2>{t.scope}</h2><fieldset disabled={busy}><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,220px),1fr))", gap: "1rem" }}>{(["workspace", "organization", "entity"] as const).map(k => <label key={k}>{t[k]}<input value={scope[k]} onChange={e => setScope(v => ({ ...v, [k]: e.target.value }))} /></label>)}</div></fieldset></section>
  {error && <p role="alert">{t.error} {error}</p>}
  {pending && <section className="panel"><p>{t.pending}</p><p>{t.command}: <code>{pending.body.command_id}</code></p><button disabled={busy || !auth.session} onClick={() => void run(pending.suffix, pending.body, pending.scope)}>{t.retry}</button></section>}
  <section className="panel workbench-panel"><h2>{t.load}</h2><form onSubmit={e => { e.preventDefault(); void run(`/plans/${encodeURIComponent(planId)}`); }}><label>{t.planId}<input required value={planId} onChange={e => setPlanId(e.target.value)} /></label><button disabled={busy || !auth.session}>{busy ? t.busy : t.load}</button></form></section>
  <section className="panel workbench-panel"><h2>{t.prepare}</h2><form onSubmit={prepare}><fieldset disabled={busy || !auth.session || Boolean(pending)}><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,220px),1fr))", gap: "1rem" }}>{field("receipt_number", t.number)}{field("posting_date", t.date)}{field("period_id", t.period)}{field("item_code", t.item)}{field("location_code", t.location)}{field("quantity", t.quantity)}{field("total_value_minor", t.value)}{field("policy_code", t.policy)}{field("organization_code", t.orgCode)}{field("entity_code", t.entityCode)}{field("reason", t.reason)}</div><button>{t.prepare}</button></fieldset></form></section>
  {view && <section className="panel workbench-panel" aria-label={t.evidence}><h2>{view.number} — {view.status === "Prepared" ? t.prepared : view.status === "Reviewed" ? t.reviewed : t.committed}</h2><p>{view.quantity} · {receiptMoney(view.total_value_minor, view.currency_precision)} {view.currency_code}</p><p>{t.authority}</p><p>{t.planId}: <code>{view.plan_id}</code></p><div style={{ overflowX: "auto" }}><table><caption>{t.evidence}</caption><thead><tr><th>{t.account}</th><th>{t.debit}</th><th>{t.credit}</th></tr></thead><tbody>{view.lines.map(line => <tr key={line.account_id}><td>{line.account_id}</td><td>{receiptMoney(line.debit_minor, view.currency_precision)}</td><td>{receiptMoney(line.credit_minor, view.currency_precision)}</td></tr>)}</tbody></table></div>
   <label>{t.reason}<input value={reason} onChange={e => setReason(e.target.value)} /></label>
   {view.status === "Prepared" && <button disabled={busy || !auth.session || !reason || Boolean(pending)} onClick={() => void run(`/plans/${view.plan_id}/review`, { command_id: command(), expected_plan_digest: view.plan_digest, reason })}>{t.review}</button>}
   {view.status === "Reviewed" && <button disabled={busy || !auth.session || !reason || Boolean(pending)} onClick={() => void run(`/plans/${view.plan_id}/commit`, { command_id: command(), expected_review_digest: view.review_digest!, reason })}>{t.commit}</button>}
   {view.status === "Committed" && view.operation === "Receipt" && <form onSubmit={e => { e.preventDefault(); if (!pending) void run(`/plans/${view.plan_id}/reversal`, { command_id: command(), reversal_number: reversalNumber, posting_date: reversalDate, period_id: reversalPeriod, reason }); }}><fieldset disabled={busy || !auth.session || Boolean(pending)}><legend>{t.reversal}</legend><label>{t.reversalNumber}<input required value={reversalNumber} onChange={e => setReversalNumber(e.target.value)} /></label><label>{t.date}<input type="date" required value={reversalDate} onChange={e => setReversalDate(e.target.value)} /></label><label>{t.period}<input required value={reversalPeriod} onChange={e => setReversalPeriod(e.target.value)} /></label><button disabled={!reason}>{t.reversal}</button></fieldset></form>}
   {([[t.source, view.plan_json], [t.reviewEvidence, view.review_json], [t.effect, view.effect_json]] as const).map(([label, json]) => json && <details key={label}><summary>{label}</summary><pre style={{ whiteSpace: "pre-wrap", overflowWrap: "anywhere" }}>{json}</pre></details>)}
  </section>}
 </main>;
}
