import { expect, test } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const base = process.env.RECONFORGE_CASH_UI_BASE_URL;
const password = process.env.RECONFORGE_CASH_UI_PASSWORD;
const output = process.env.RECONFORGE_CASH_UI_OUTPUT;
test.skip(!base || !password || !output, "PROD031 requires the explicit synthetic PostgreSQL HTTPS cash fixture; review 2026-10-10");
test.use({ ignoreHTTPSErrors: true });

test("real HTTPS cash posting, exact retry and allocation readback settle the approved invoice", async ({ page }) => {
  test.setTimeout(120_000);
  const evidence: Record<string, unknown> = { synthetic_only: true };
  await page.goto(`${base}/receivables`);
  await page.getByLabel("Tenant ID").fill("cash-a"); await page.getByLabel("Username").fill("cashier"); await page.getByLabel("Password", { exact: true }).fill(password!);
  const loggedIn = page.waitForResponse((response) => response.url().endsWith("/auth/browser/login"));
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  const login = await loggedIn; expect(login.status()).toBe(200); const csrf = (await login.json()).csrf_token as string;
  const cookie = (await page.context().cookies()).find((item) => item.name.includes("session"));
  expect(cookie).toMatchObject({ httpOnly: true, secure: true });
  await page.getByRole("combobox", { name: "Authorized workspace", exact: true }).selectOption("cash-work");
  await page.getByRole("button", { name: "Review INV-CASH-A", exact: true }).click();
  const cash = page.getByRole("region", { name: "Cash receipts and allocations", exact: true });
  const newInvoice = page.locator("details.ar-draft > summary");
  await expect(page.getByLabel("Invoice number", { exact: true })).not.toBeVisible();
  await newInvoice.focus(); await page.keyboard.press("Enter");
  await expect(page.getByLabel("Invoice number", { exact: true })).toBeVisible();
  await page.keyboard.press("Space");
  await expect(page.getByLabel("Invoice number", { exact: true })).not.toBeVisible();
  await expect(cash).toContainText("Reauthenticate above");
  const before = await page.evaluate(async ({ proof }) => (await fetch("/api/v1/receivables/receipts", { method: "POST", headers: { "Content-Type": "application/json", "X-ReconForge-Tenant": "cash-a", "X-ReconForge-Workspace": "cash-work", "X-ReconForge-CSRF": proof }, body: JSON.stringify({ receipt_number: "DENIED-BEFORE-STEPUP", customer_code: "CUS-A", receipt_date: "2026-10-03", currency_code: "USD", amount_minor: 1 }) })).status, { proof: csrf });
  expect(before).toBe(403); evidence.before_stepup_status = before;
  await page.getByLabel("Password", { exact: true }).fill(password!);
  const stepUp = page.waitForResponse((response) => response.url().endsWith("/auth/step-up"));
  await page.getByRole("button", { name: "Reauthenticate for cash actions", exact: true }).click();
  expect((await stepUp).status()).toBe(200);
  await page.getByRole("combobox", { name: "Authorized workspace", exact: true }).selectOption("cash-work");
  await page.getByRole("button", { name: "Review INV-CASH-A", exact: true }).click();
  await cash.getByLabel("Receipt number", { exact: true }).fill("CASH-UI-001"); await cash.getByLabel("Receipt date", { exact: true }).fill("2026-10-03");
  await cash.getByLabel("Received amount · minor units", { exact: true }).fill("1376"); await cash.getByLabel("Apply now to this invoice · minor units", { exact: true }).fill("400");
  const writes: string[] = [];
  let postedId = "";
  await page.route("**/api/v1/receivables/receipts", async (route) => {
    if (route.request().method() !== "POST") return route.continue();
    writes.push(route.request().postData()!);
    const response = await route.fetch(); expect(response.status()).toBe(200);
    const record = await response.json(); postedId = record.id;
    evidence.initial_post = record;
    await route.abort("failed");
  });
  await cash.getByRole("button", { name: "Review cash action", exact: true }).click();
  expect(writes).toHaveLength(0);
  await expect(cash.getByRole("region", { name: "Review cash action", exact: true })).toBeFocused();
  await cash.getByRole("button", { name: "Confirm financial action", exact: true }).click();
  await expect(cash.getByRole("button", { name: "Retry the exact request", exact: true })).toBeVisible();
  await expect(cash.getByLabel("Receipt number", { exact: true })).toBeDisabled();
  await expect(page.getByRole("button", { name: "Refresh records", exact: true })).toBeDisabled();
  await expect(page.getByRole("button", { name: "Review INV-CASH-A", exact: true })).toBeDisabled();
  await newInvoice.focus(); await page.keyboard.press("Enter");
  await expect(page.getByLabel("Invoice number", { exact: true })).toBeDisabled();
  await expect(page.getByRole("button", { name: "Save draft", exact: true })).toBeDisabled();
  await page.keyboard.press("Space");
  await page.unroute("**/api/v1/receivables/receipts");
  const retried = page.waitForResponse((response) => response.url().endsWith("/receivables/receipts") && response.request().method() === "POST");
  await cash.getByRole("button", { name: "Retry the exact request", exact: true }).click();
  const retry = await retried; expect(retry.status()).toBe(200); expect(retry.request().postData()).toBe(writes[0]); evidence.exact_retry_same_payload = true;
  await expect(cash).toContainText("server confirmed the cash action");
  const evidenceDetails = cash.locator("details.ar-evidence > summary");
  await expect(cash.getByText(postedId, { exact: true })).not.toBeVisible();
  await evidenceDetails.focus(); await page.keyboard.press("Enter");
  await expect(cash.getByText(postedId, { exact: true })).toBeVisible();
  await page.keyboard.press("Space");
  await expect(cash.getByText(postedId, { exact: true })).not.toBeVisible();
  await cash.getByLabel("Additional allocation · minor units", { exact: true }).fill("200");
  await page.route(`**/api/v1/receivables/receipts/${postedId}/allocate`, async (route) => {
    const result = await route.fetch(); expect(result.status()).toBe(200); evidence.lost_allocation_response = await result.json(); await route.abort("failed");
  });
  await cash.getByRole("button", { name: "Review allocation", exact: true }).click(); await cash.getByRole("button", { name: "Confirm financial action", exact: true }).click();
  await cash.getByRole("button", { name: "Refresh authoritative receipt and invoice", exact: true }).click();
  await expect(cash).toContainText("They do not identify whether the earlier request succeeded");
  await expect(cash.getByLabel("Additional allocation · minor units", { exact: true })).toBeDisabled();
  await page.unroute(`**/api/v1/receivables/receipts/${postedId}/allocate`);
  await cash.getByRole("button", { name: "Use these current balances", exact: true }).click();
  await cash.getByLabel("Additional allocation · minor units", { exact: true }).fill("776");
  await cash.getByRole("button", { name: "Review allocation", exact: true }).click(); await cash.getByRole("button", { name: "Confirm financial action", exact: true }).click();
  await expect(cash).toContainText("This invoice has no approved open balance");
  const states = await page.evaluate(async ({ id, proof }) => {
    const headers = { "Content-Type": "application/json", "X-ReconForge-Tenant": "cash-a", "X-ReconForge-Workspace": "cash-work", "X-ReconForge-CSRF": proof };
    const receipt = await (await fetch(`/api/v1/receivables/receipts/${id}`, { headers })).json();
    const invoice = await (await fetch(`/api/v1/receivables/invoices/${receipt.allocations[0].invoice_id}`, { headers })).json();
    const exposure = await (await fetch("/api/v1/receivables/credit-exposure/CUS-A", { headers })).json();
    const noCsrfHeaders = { ...headers }; delete (noCsrfHeaders as Record<string, string>)["X-ReconForge-CSRF"];
    const noCsrf = await fetch(`/api/v1/receivables/receipts/${id}/allocate`, { method: "POST", headers: noCsrfHeaders, body: JSON.stringify({ invoice_id: invoice.id, amount_minor: 1, expected_version: receipt.row_version }) });
    const sibling = await fetch(`/api/v1/receivables/receipts/${id}`, { headers: { ...headers, "X-ReconForge-Organization": "cash-org", "X-ReconForge-Legal-Entity": "cash-entity-b" } });
    const foreign = await fetch(`/api/v1/receivables/receipts/${id}`, { headers: { ...headers, "X-ReconForge-Tenant": "cash-b" } });
    return { receipt, invoice, exposure, noCsrf: noCsrf.status, sibling: sibling.status, foreign: foreign.status };
  }, { id: postedId, proof: csrf });
  expect(states.receipt).toMatchObject({ amount_minor: 1376, allocated_minor: 1376, unallocated_minor: 0, row_version: 3, organization_id: "cash-org", legal_entity_id: "cash-entity-a" });
  expect(states.invoice).toMatchObject({ status: "Paid", outstanding_minor: 0, row_version: 6 }); expect(states.exposure.exposure_minor).toBe(0);
  expect(states.noCsrf).toBe(403); expect([400, 403]).toContain(states.sibling); expect([401, 403]).toContain(states.foreign); evidence.final = states;
  for (const locale of ["en", "ar"] as const) {
    if (locale === "ar") await page.getByTestId("locale-toggle").click();
    await expect(page.getByRole("main")).toHaveAttribute("dir", locale === "ar" ? "rtl" : "ltr");
    expect((await new AxeBuilder({ page }).include("main").withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]);
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: join(output!, `cash-${locale}.png`), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await expect(newInvoice.locator("..")).not.toHaveAttribute("open", "");
    const localizedCash = page.locator(".ar-cash");
    await localizedCash.locator("details.ar-evidence > summary").focus(); await page.keyboard.press("Enter");
    await expect(localizedCash.getByText(postedId, { exact: true })).toBeVisible();
    await page.keyboard.press("Space");
    await expect(localizedCash.getByText(postedId, { exact: true })).not.toBeVisible();
    await page.locator(".ar-cash").screenshot({ path: join(output!, `cash-panel-mobile-${locale}.png`) });
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: join(output!, `cash-mobile-${locale}.png`), fullPage: true });
    await page.setViewportSize({ width: 1280, height: 900 });
  }
  evidence.accessibility = { en: "no WCAG2A/AA/2.1AA axe violations", ar: "no WCAG2A/AA/2.1AA axe violations", mobile_width: 390 };
  evidence.progressive_disclosure = { new_invoice_collapsed_during_review: true, receipt_identity_hidden_until_requested: true, keyboard_enter_space_en_ar: true };
  writeFileSync(join(output!, "browser.json"), JSON.stringify(evidence, null, 2));
});
