"""Safe, manifest-driven connector SDK contracts."""

from reconforge.connectors.manifest import (
    AuthenticationMethod,
    ConnectorCapability,
    ConnectorKind,
    ConnectorManifest,
    DataClassification,
    RetryPolicy,
    SupportLevel,
)
from reconforge.connectors.package import (
    ConnectorPackageError,
    PublisherKeyStatus,
    TrustedPublisherKey,
    TrustedPublisherRegistry,
    load_verified_package,
)
from reconforge.connectors.rest_reference import (
    REFERENCE_REST_MANIFEST,
    ReferenceRestConnector,
    ReferenceRestPage,
    ReferenceRestRead,
    ReferenceRestRecord,
    reference_rest_registration,
)
from reconforge.connectors.sftp_reference import (
    SFTP_REFERENCE_ENDPOINT,
    SFTP_REFERENCE_MANIFEST,
    ReferenceSftpConnector,
    SftpConnectorRegistration,
    SftpFileRead,
    SftpRead,
    SftpRemoteFile,
    sftp_reference_registration,
)
from reconforge.connectors.writeback import (
    WritebackAcknowledgement,
    WritebackApproval,
    WritebackError,
    WritebackIntent,
    WritebackPolicy,
    WritebackStatus,
    acknowledge_writeback,
    approve_writeback,
    complete_compensation,
    dispatch_writeback,
    request_compensation,
)

__all__ = [
    "AuthenticationMethod",
    "ConnectorCapability",
    "ConnectorKind",
    "ConnectorManifest",
    "ConnectorPackageError",
    "REFERENCE_REST_MANIFEST",
    "ReferenceRestConnector",
    "ReferenceRestPage",
    "ReferenceRestRead",
    "ReferenceRestRecord",
    "reference_rest_registration",
    "WritebackAcknowledgement",
    "WritebackApproval",
    "WritebackError",
    "WritebackIntent",
    "WritebackPolicy",
    "WritebackStatus",
    "acknowledge_writeback",
    "approve_writeback",
    "complete_compensation",
    "dispatch_writeback",
    "request_compensation",
    "SFTP_REFERENCE_ENDPOINT",
    "SFTP_REFERENCE_MANIFEST",
    "ReferenceSftpConnector",
    "SftpConnectorRegistration",
    "SftpFileRead",
    "SftpRead",
    "SftpRemoteFile",
    "sftp_reference_registration",
    "DataClassification",
    "PublisherKeyStatus",
    "RetryPolicy",
    "SupportLevel",
    "TrustedPublisherKey",
    "TrustedPublisherRegistry",
    "load_verified_package",
]
