"""Domain reference models and repositories for local enterprise foundations."""

from __future__ import annotations

from reconforge.domain.jobs import (
    ALLOWED_TRANSITIONS,
    JOB_SCHEMA_VERSION,
    DurableJob,
    JobInvariantError,
    JobLease,
    JobOutputManifest,
    JobStatus,
    JobTransition,
)
from reconforge.domain.models import (
    AccountingDimension,
    AccountingDimensionValue,
    AuditEventReference,
    Branch,
    ChartOfAccounts,
    Currency,
    EvidenceReference,
    FinanceJournal,
    FinancialAccount,
    InventoryCountLine,
    InventoryCountSession,
    InventoryItem,
    InventoryLocation,
    InventoryLot,
    InventoryMovement,
    InventoryMovementLine,
    InventoryReorderRule,
    LedgerEntry,
    LedgerLine,
    LegalEntity,
    Organization,
    Period,
    Permission,
    ReconciliationReference,
    Role,
    UnitOfMeasure,
    UserReference,
    Warehouse,
    Workspace,
)
from reconforge.domain.protocols import (
    AuditEventRepositoryProtocol,
    DomainUnitOfWorkFactory,
    DomainUnitOfWorkProtocol,
    PeriodRepositoryProtocol,
    WorkspaceRepositoryProtocol,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "JOB_SCHEMA_VERSION",
    "DurableJob",
    "JobInvariantError",
    "JobLease",
    "JobOutputManifest",
    "JobStatus",
    "JobTransition",
    "AccountingDimension",
    "AccountingDimensionValue",
    "AuditEventReference",
    "AuditEventRepositoryProtocol",
    "Branch",
    "ChartOfAccounts",
    "Currency",
    "DomainUnitOfWorkFactory",
    "DomainUnitOfWorkProtocol",
    "EvidenceReference",
    "FinanceJournal",
    "FinancialAccount",
    "InventoryCountLine",
    "InventoryCountSession",
    "InventoryItem",
    "InventoryLocation",
    "InventoryLot",
    "InventoryMovement",
    "InventoryMovementLine",
    "InventoryReorderRule",
    "LedgerEntry",
    "LedgerLine",
    "LegalEntity",
    "Organization",
    "Period",
    "PeriodRepositoryProtocol",
    "Permission",
    "ReconciliationReference",
    "Role",
    "UnitOfMeasure",
    "UserReference",
    "Warehouse",
    "Workspace",
    "WorkspaceRepositoryProtocol",
]
