"""Closed source-return repository contract."""
from __future__ import annotations

from typing import Any, Protocol

from reconforge.domain.finance_posting import PostingActor
from reconforge.domain.supplier_returns import SupplierReturnPreparation


class SupplierReturnsRepository(Protocol):
    def prepare(self, request: SupplierReturnPreparation, *, command_id: str, actor: PostingActor) -> dict[str, Any]: ...
    def get(self, plan_id: str, *, actor: PostingActor) -> dict[str, Any]: ...
    def list_plans(self, order_id: str, *, actor: PostingActor) -> dict[str, Any]: ...
    def review(self, plan_id: str, *, expected_plan_digest: str, command_id: str, reason: str, actor: PostingActor) -> dict[str, Any]: ...
    def post(self, plan_id: str, *, expected_plan_digest: str, command_id: str, reason: str, actor: PostingActor) -> dict[str, Any]: ...
    def cancel(self, plan_id: str, *, expected_plan_digest: str, command_id: str, reason: str, actor: PostingActor) -> dict[str, Any]: ...
